<?
$_LANG_TEXT2 = array (
	"screenunlockpwdregxtext"=>array("CN"=>"通过仅组合字母字符和数字输入 8 到 16 个字符内的密码.", "KR"=>"비밀번호는 영문자와 숫자만 조합하여 8~16자 이내로 입력.", "EN" => "Enter a password within 8 to 16 characters by combining only alphabet letters and numbers." ),
	"adminpwdregxtext"=>array("CN"=>"输入 8 到 16 个字符以内的密码，包括至少 3 种大写字母(A~Z)、小写字母(a~z)、数字(0~9),殊字符(!@#$%^&*).", "KR"=>"비밀번호는 영문 대/소문자(A~Z,a~z), 숫자(0~9), 특수문자(!@#$%^&*)를 3개 이상 포함하여 8~16자 이내로 입력해야 합니다.", "EN" => "Enter the password within 8 to 16 characters, including at least 3 types uppercase letters(A~Z), lowercase letters(a~z), numbers(0~9) and special characters(!@#$%^&*)." ),
	"empnoregtext"=> array("JP"=>"ID must be entered with uppercase and lowercase letters and 5 to 12 numbers.", "CN"=>"ID 必须输入大小写字母和 5 到 12 位数字.", "KR"=>"아이디는 영문 대문자,소문자,숫자를 사용해 5~12자리로 입력해야합니다.", "EN" => "ID must be entered with uppercase and lowercase letters and 5 to 12 numbers." ),
	"centerzoneserviceconfig"=> array("CN"=>"","KR"=>"검사 구역별 서비스 설정","EN"=>""),
	"addcenterzone"=> array("CN"=>"","KR"=>"검사 구역 추가","EN"=>""),
	"registerationoknntext"=>array("CN"=>"已注册。", "KR"=>"등록되었습니다.", "EN" => "Registered." ),
	"updateoknntext"=>array("CN"=>"已修改。", "KR"=>"수정되었습니다.", "EN" => "Updated." ),
	"deleteoknntext"=>array("CN"=>"已删除。", "KR"=>"삭제되었습니다.", "EN" => "Deleted." ),
	"canceloknntext"=>array("CN"=>"已取消.", "KR"=>"취소되었습니다.", "EN" => "Cancelled." ),
	"proc_error"=>array("CN"=>"在处理过程中发生错误。", "KR"=>"처리중 오류가 발생했습니다.", "EN" => "An error occurred during processing." ),
	"proc_ok"=>array("CN"=>"处理成功.", "KR"=>"정상적으로 처리되었습니다.", "EN" => "Processed successfully." ),
	"invaliddatatext"=>array("CN"=>"无效数据", "KR"=>"유효하지 않은 데이터입니다.", "EN" => "Invalid data" ),
	"duplicatedatatext"=>array("CN"=>"是重复数据.", "KR"=>"중복된 데이터입니다.", "EN" => "It is duplicate data." ),
	"savetext"=>array("CN"=>"已保存。", "KR"=>"저장되었습니다.", "EN" => "Saved." ),
	"temppassnumber"=>array("CN"=>"", "KR"=>"임시출입증번호", "EN" => "임시출입증번호" ),
	"settingtext"=>array("CN"=>"Setting", "KR"=>"설정", "EN" => "Setting" ),
	"addouterlinktext"=>array("CN"=>"외부링크 추가", "KR"=>"외부링크 추가", "EN" => "외부링크 추가" ),
	"outerlinktext"=>array("CN"=>"외부링크", "KR"=>"외부링크", "EN" => "외부링크" ),
	"inputlinkurl"=>array("CN"=>"링크주소를 입력하세요", "KR"=>"링크주소를 입력하세요", "EN" => "링크주소를 입력하세요" ),
	"inputlinktitle"=>array("CN"=>"링크제목을 입력하세요", "KR"=>"링크제목을 입력하세요", "EN" => "링크제목을 입력하세요" ),
	"adaptkiosk"=>array("CN"=>"", "KR"=>"적용 키오스크", "EN" => "" ),
	"notexistkioskinfo"=>array("CN"=>"", "KR"=>"등록된 키오스크 정보가 없습니다.", "EN" => "" ),
	"addnremove"=>array("CN"=>"", "KR"=>"추가/삭제", "EN" => "" ),
	"totalconfig"=>array("CN"=>"", "KR"=>"전체 설정", "EN" => "" ),
	"fileimportpolicy"=>array("CN"=>"", "KR"=>"파일 반입 예외 설정", "EN" => "" ),
	"targetdiv"=>array("CN"=>"", "KR"=>"대상구분", "EN" => "" ),
	"applicationperiod"=>array("CN"=>"", "KR"=>"적용 기간", "EN" => "" ),
	"policyname"=>array("CN"=>"", "KR"=>"정책명", "EN" => "" ),
	"exceptiontarget"=>array("CN"=>"", "KR"=>"예외대상", "EN" => "" ),
	"filehash"=>array("CN"=>"", "KR"=>"파일해시", "EN" => "" ),
	"additionpolicy"=>array("CN"=>"", "KR"=>"정책추가", "EN" => "" ),
	"exceptionfile"=>array("CN"=>"", "KR"=>"예외적용파일", "EN" => "" ),
	"selecttargetdiv"=>array("CN"=>"", "KR"=>"대상구분선택", "EN" => "" ),
	"specifiedfile"=>array("CN"=>"", "KR"=>"지정파일", "EN" => "" ),
	"inputfilehash"=>array("CN"=>"", "KR"=>"파일해시(MD5) 값을 입력하세요", "EN" => "" ),
	"inputdescription"=>array("CN"=>"", "KR"=>"설명을 입력하세요", "EN" => "" ),
	"inputsearchkeyword"=>array("CN"=>"", "KR"=>"검색어를 입력하세요", "EN" => "" ),
	"inputnameorid"=>array("CN"=>"", "KR"=>"이름 또는 영문 아이디를 입력하세요", "EN" => "" ),
	"inputdept"=>array("CN"=>"", "KR"=>"부서명을 입력하세요", "EN" => "" ),
	"begindate"=>array("CN"=>"", "KR"=>"시작일", "EN" => "" ),
	"enddate"=>array("CN"=>"", "KR"=>"종료일", "EN" => "" ),
	"assetimportinfo"=>array("CN"=>"", "KR"=>"자산 반입정보", "EN" => "" ),
	"managenumber"=>array("CN"=>"", "KR"=>"관리번호", "EN" => "" ),
	"fileserversend"=>array("CN"=>"", "KR"=>"파일서버전송", "EN" => "" ),
	"agreeTitle"=>array("CN"=>"", "KR"=>"동의 및 안내 제목", "EN" => "" ),
	"agreeContent"=>array("CN"=>"", "KR"=>"동의 및 안내 내용", "EN" => "" ),
	"agreeNeed"=>array("CN"=>"", "KR"=>"동의 필수", "EN" => "" ),
	"asset"=>array("CN"=>"", "KR"=>"자산", "EN" => "" ),
	"file"=>array("CN"=>"", "KR"=>"파일", "EN" => "" ),
	"belongdivtext"=>array("CN"=>"", "KR"=>"소속구분", "EN" => "" ),
	"fileimport"=>array("CN"=>"", "KR"=>"파일반입", "EN" => "" ),
	"importdate"=>array("CN"=>"", "KR"=>"반입일자", "EN" => "" ),
	"importdiv"=>array("CN"=>"", "KR"=>"반입구분", "EN" => "" ),
	"admin"=>array("CN"=>"", "KR"=>"관리자", "EN" => "" ),
	"staff"=>array("CN"=>"", "KR"=>"임직원", "EN" => "" ),
	"staffinfo"=>array("CN"=>"", "KR"=>"임직원정보", "EN" => "" ),
	"datesearchtext"=>array("CN"=>"", "KR"=>"일자 검색", "EN" => "" ),
	"fileimporttimes"=>array("CN"=>"", "KR"=>"파일반입 횟수", "EN" => "" ),
	"assetimporttext"=>array("CN"=>"", "KR"=>"자산반입", "EN" => "" ),
	"usbofferinfotext"=>array("CN"=>"", "KR"=>"사내 USB 지급정보", "EN" => "" ),
	"virusscantext"=>array("CN"=>"", "KR"=>"바이러스 검사", "EN" => "" ),
	"badfilescantext"=>array("CN"=>"", "KR"=>"위변조 검사", "EN" => "" ),
	"filecopytext"=>array("CN"=>"", "KR"=>"파일 복사", "EN" => "" ),
	"issuepurposetext"=>array("CN"=>"", "KR"=>"발급사유", "EN" => "" ),
	"beforeexportsearchtext"=>array("CN"=>"", "KR"=>"미반출조회", "EN" => "" ),
	"starttime"=>array("CN"=>"", "KR"=>"시작시간", "EN" => "" ),
	"endtime"=>array("CN"=>"", "KR"=>"종료시간", "EN" => "" ),
	"scanduringtime"=>array("CN"=>"", "KR"=>"검사소요시간", "EN" => "" ),
	"managerinfo"=>array("CN"=>"", "KR"=>"매니저정보", "EN" => "" ),
	"synchronization"=>array("CN"=>"", "KR"=>"동기화", "EN" => "" ),
	"accessauthtext"=>array("CN"=>"", "KR"=>"접근권한", "EN" => "" ),
	"accessauthsettingtext"=>array("CN"=>"", "KR"=>"접근권한설정", "EN" => "" ),
	"accountregisttext"=>array("CN"=>"", "KR"=>"VCS 계정생성", "EN" => "" ),
	"adminnametext"=>array("CN"=>"", "KR"=>"관리자명", "EN" => "" ),
	"inputfilename"=>array("CN"=>"", "KR"=>"파일명을 입력하세요", "EN" => "" ),
	"fileimportapplylist"=>array("CN"=>"", "KR"=>"파일 반입 예외 신청내역", "EN" => "" ),
	"importapplytext"=>array("CN"=>"", "KR"=>"반입 예외 신청", "EN" => "" ),
	"approvewaittext"=>array("CN"=>"", "KR"=>"승인대기", "EN" => "" ),
	"applyreason"=>array("CN"=>"", "KR"=>"신청사유", "EN" => "" ),
	"approver"=>array("CN"=>"", "KR"=>"승인자", "EN" => "" ),
	"approvedate"=>array("CN"=>"", "KR"=>"승인일자", "EN" => "" ),
	"cantupdate_applydateexceed"=>array("CN"=>"", "KR"=>"적용기간이 종료되어 수정할 수 없습니다.", "EN" => "" ),
	"cantdelete_applydateexceed"=>array("CN"=>"", "KR"=>"적용기간이 종료되어 삭제할 수 없습니다.", "EN" => "" ),
	"applydateclosed"=>array("CN"=>"", "KR"=>"적용기간이 종료되었습니다.", "EN" => "" ),
	"fileimportvisit"=>array("CN"=>"", "KR"=>"파일반입 출입", "EN" => "" ),
	"passcardvisit"=>array("CN"=>"", "KR"=>"임시방문증 발급 출입", "EN" => "" ),
	"dailyrentalstatus"=>array("CN"=>"", "KR"=>"일별 물품대여현황", "EN" => "" ),
	"monthlyrentalstatus"=>array("CN"=>"", "KR"=>"월별 물품대여현황", "EN" => "" ),
	"specificday"=>array("CN"=>"", "KR"=>"특정일", "EN" => "" ),
	"everyday"=>array("CN"=>"", "KR"=>"매일", "EN" => "" ),
	"rentalcount"=>array("CN"=>"", "KR"=>"대여건수", "EN" => "" ),
	"hdbsyncwork"=>array("CN"=>"", "KR"=>"인사디비동기화", "EN" => "" ),
	"userdatadeletework"=>array("CN"=>"", "KR"=>"보유기간 경과 데이타삭제", "EN" => "" ),
	"worklogtext"=>array("CN"=>"", "KR"=>"작업로그", "EN" => "" ),
	"worktimetext"=>array("CN"=>"", "KR"=>"작업일시", "EN" => "" ),
	"workresulttext"=>array("CN"=>"", "KR"=>"작업결과", "EN" => "" ),
	"scannumber"=>array("CN"=>"", "KR"=>"점검번호", "EN" => "" ),
	"customquerymaxrows"=> array("CN"=>"", "KR"=>"조회 가능한 최대 데이터 건수는 1,000 건 입니다.", "EN" => "" ),
	"allowonlyselecttext"=> array("CN"=>"", "KR"=>"Select 쿼리 실행만 허용 됩니다.", "EN" => "" ),
	"queryresulttext"=> array("CN"=>"", "KR"=>"쿼리 결과", "EN" => "" ),
	"logintimetext"=> array("CN"=>"", "KR"=>"로그인 시간", "EN" => "" ),
	"logouttimetext"=> array("CN"=>"", "KR"=>"로그아웃 시간", "EN" => "" ),
	"loginstatustext"=> array("CN"=>"", "KR"=>"로그인 여부", "EN" => "" ),
	"max31days"=> array("CN"=>"", "KR"=>"최대31일", "EN" => "" ),
	"dailyvisitstatisticstext"=> array("CN"=>"", "KR"=>"일별 출입통계", "EN" => "" ),
	"dailyscanstatisticstext"=> array("CN"=>"", "KR"=>"일별 점검통계", "EN" => "" ),
	"scanresultstatisticstext"=> array("CN"=>"", "KR"=>"점검결과통계", "EN" => "" ),
	"scanresultlisttext"=> array("CN"=>"", "KR"=>"점검결과내역", "EN" => "" ),
	"canceltext"=> array("CN"=>"", "KR"=>"취소", "EN" => "" ),
	"badextentionstatustext"=> array("CN"=>"", "KR"=>"위변조의심 현황", "EN" => "" ),
	"badextentionlisttext"=> array("CN"=>"", "KR"=>"위변조의심 내역", "EN" => "" ),
	"adapting"=> array("CN"=>"", "KR"=>"적용중", "EN" => "" ),
	"applynumbertext"=> array("CN"=>"", "KR"=>"신청번호", "EN" => "" ),
	"carouttime"=> array("CN"=>"", "KR"=>"출차시간", "EN" => "" ),
	"scancounttext"=> array("CN"=>"", "KR"=>"점검건수", "EN" => "" )
	,"workresultdetails"=>array("JP"=>"", "CN"=>"", "KR"=>"작업결과 상세", "EN" => "" )
	,"informationprotectionpledge"=>array("JP"=>"", "CN"=>"", "KR"=>"정보보호서약서", "EN" => "" )
	,"contentreplaceword"=>array("JP"=>"", "CN"=>"", "KR"=>"내용 치환 단어", "EN" => "" )
	,"visitpurposereplacetext"=>array("JP"=>"", "CN"=>"", "KR"=>"출입 신청시 입력한 '방문목적' 으로 치환", "EN" => "" )
	,"centerpositiontext"=>array("JP"=>"", "CN"=>"", "KR"=>"센터위치", "EN" => "" )
	,"writeoktext"=>array("JP"=>"", "CN"=>"", "KR"=>"작성완료", "EN" => "" )
	,"worknumbertext"=>array("JP"=>"", "CN"=>"", "KR"=>"작업번호", "EN" => "" )
	,"visitdatetext"=>array("JP"=>"", "CN"=>"", "KR"=>"방문일자", "EN" => "" )
	,"inofficetimetext"=>array("JP"=>"", "CN"=>"", "KR"=>"입실시간", "EN" => "" )
	,"outofficetimetext"=>array("JP"=>"", "CN"=>"", "KR"=>"퇴실시간", "EN" => "" )
	,"inofficewaittext"=>array("JP"=>"", "CN"=>"", "KR"=>"입실대기", "EN" => "" )
	,"inofficeoktext"=>array("JP"=>"", "CN"=>"", "KR"=>"입실완료", "EN" => "" )
	,"outofficeoktext"=>array("JP"=>"", "CN"=>"", "KR"=>"퇴실완료", "EN" => "" )
	,"inofficeaccesstext"=>array("JP"=>"", "CN"=>"", "KR"=>"입실처리", "EN" => "" )
	,"outofficeaccesstext"=>array("JP"=>"", "CN"=>"", "KR"=>"퇴실처리", "EN" => "" )
	,"inofficeconfirmertext"=>array("JP"=>"", "CN"=>"", "KR"=>"입실확인자", "EN" => "" )
	,"outofficeconfirmertext"=>array("JP"=>"", "CN"=>"", "KR"=>"퇴실확인자", "EN" => "" )
	,"visitnumbertext"=>array("JP"=>"", "CN"=>"", "KR"=>"출입번호", "EN" => "" )
	,"confirmertext"=>array("JP"=>"", "CN"=>"", "KR"=>"확인자", "EN" => "" )
	,"inofficeaccesscanceltext"=>array("JP"=>"", "CN"=>"", "KR"=>"입실처리취소", "EN" => "" )
	,"outofficeaccesscanceltext"=>array("JP"=>"", "CN"=>"", "KR"=>"퇴실처리취소", "EN" => "" )
	,"user_agree_list"=>array("JP"=>"", "CN"=>"", "KR"=>"동의 및 서약서 내역", "EN" => "" )
	,"officeinandouttimetext"=>array("JP"=>"", "CN"=>"", "KR"=>"입/퇴실 시간", "EN" => "" )
	,"notwritten"=>array("JP"=>"", "CN"=>"", "KR"=>"미작성", "EN" => "" )
	,"note"=>array("JP"=>"", "CN"=>"", "KR"=>"비고", "EN" => "" )
	,"noupdatetext"=>array("JP"=>"", "CN"=>"", "KR"=>"업데이트 내역이 없습니다", "EN" => "" )
	,"idccheckinoutdetails"=>array("JP"=>"", "CN"=>"", "KR"=>"IDC 입/퇴실 내역", "EN" => "" )
	,"setauthdetails"=>array("JP"=>"", "CN"=>"", "KR"=>"세부권한지정", "EN" => "" )
	,"mgtfilesignitureinfo"=>array("JP"=>"", "CN"=>"", "KR"=>"파일시그니처정보관리", "EN" => "" )
	,"createtext"=>array("JP"=>"", "CN"=>"", "KR"=>"생성", "EN" => "" )
	,"downloadandprinttext"=>array("JP"=>"", "CN"=>"", "KR"=>"다운로드/인쇄", "EN" => "" )
	,"setpageaccesstext"=>array("JP"=>"", "CN"=>"", "KR"=>"페이지 접근권한 설정", "EN" => "" )
	,"pageaccessauth"=>array("JP"=>"", "CN"=>"", "KR"=>"페이지 접근권한", "EN" => "" )
	,"datadeletedayterms"=>array("JP"=>"", "CN"=>"", "KR"=>"데이터 삭제주기", "EN" => "" )
	,"managesecurityusb"=>array("JP"=>"", "CN"=>"", "KR"=>"보안USB관리", "EN" => "" )
	,"managedocument"=>array("JP"=>"", "CN"=>"", "KR"=>"문서관리", "EN" => "" )
	,"idcreporttitle"=>array("JP"=>"", "CN"=>"", "KR"=>"문서 제목", "EN" => "" )
	,"idcvisitorreporttext"=>array("JP"=>"","CN"=>"", "KR"=>"유지보수결과서", "EN" => "" )
	,"idcmanagerreporttext"=>array("JP"=>"","CN"=>"", "KR"=>"외부출입지원 체크리스트", "EN" => "" )
	,"reportitemtext"=>array("JP"=>"","CN"=>"", "KR"=>"작성항목", "EN" => "" )
	,"reportitemtype"=>array("JP"=>"","CN"=>"", "KR"=>"작성유형", "EN" => "" )
	,"textline"=>array("JP"=>"","CN"=>"", "KR"=>"문자열", "EN" => "" )
	,"textarea"=>array("JP"=>"","CN"=>"", "KR"=>"문자열 (여러줄)", "EN" => "" )
	,"inputcheckitem"=>array("JP"=>"","CN"=>"", "KR"=>"점검 항목을 입력하세요", "EN" => "" )
	,"inputreportitem"=>array("JP"=>"","CN"=>"", "KR"=>"작성 항목을 입력하세요", "EN" => "" )
	,"writeidcmanagerreport"=>array("JP"=>"","CN"=>"", "KR"=>"체크리스트작성", "EN" => "" )
	,"modifyidcmanagerreport"=>array("JP"=>"","CN"=>"", "KR"=>"체크리스트수정", "EN" => "" )
	,"visitorcheckoutbatchyn"=>array("JP"=>"","CN"=>"", "KR"=>"방문자퇴실처리배치실행", "EN" => "" )
	,"visitorcheckoutprocess"=>array("JP"=>"","CN"=>"", "KR"=>"방문자퇴실처리", "EN" => "" )
	,"carryinmediatext"=>array("JP"=>"","CN"=>"", "KR"=>"실물 반입", "EN" => "" )
	,"managepageaccessauth"=>array("JP"=>"", "CN"=>"", "KR"=>"그룹권한관리", "EN" => "" )
	,"pageaccessauthusedlist"=>array("JP"=>"", "CN"=>"", "KR"=>"권한 그룹 사용자", "EN" => "" )
);


$_LANG_TEXT = array_merge($_LANG_TEXT, $_LANG_TEXT2);
?>