<?php

$_LANG_TEXT = array (
	"noneresult"=>array("JP"=>"0","CN"=>"没有找到结果。", "KR"=>"찾은 결과가 없습니다.", "EN" => "No search results found." ),
	"procsuccess"=>array("JP"=>"0","CN"=>"", "KR"=>"성공", "EN" => "Success."), 
	"procfail"=>array("JP"=>"0","CN"=>"", "KR"=>"실패", "EN" => "Fail." ),
	"inputidpleasenntext"=>array("JP"=>"0","CN"=>"请输入ID。", "KR"=>"아이디를 입력하세요.", "EN" => "Type in the ID." ), 
	"inputpwdpleasenntext"=>array("JP"=>"0","CN"=>"请输入密码。", "KR"=>"비밀번호를 입력하세요.", "EN" => "Type in the password." ),
	"deleteuserornotexistuserenntext"=>array("JP"=>"0","CN"=>"不存在或已经删除的用户。","KR"=>"삭제되었거나 존재하지 않는 사용자 입니다.", "EN" => "This user was deleted or doesn’t exist."), 
	"notfoundidnntext"=>array("JP"=>"0","CN"=>"用户名不存在。", "KR"=>"아이디가 존재 하지 않습니다.","EN" => "The ID doesn’t exist." ), 
	"notfoundpwdnntext"=>array("JP"=>"0","CN"=>"密码不正确。","KR"=>"비밀번호가 일치하지 않습니다.", "EN" => "The password doesn’t match." ),
	"samepwdchangetext"=>array("JP"=>"0","CN"=>"", "KR"=>"이전 비밀번호와 동일합니다. 다른 비밀번호로 변경해 주세요", "EN" => "" ), 
	"pwdchangeoknlogintext"=>array("JP"=>"0","CN"=>"", "KR"=>"비밀번호가 변경되었습니다. 다시 로그인하여 주세요.", "EN" => "" ),
	"connectfail"=>array("JP"=>"0","CN"=>"连接状态", "KR"=>"접속실패", "EN" => "Connection Fail" ),
	"termwronginputnntext"=>array("JP"=>"0","CN"=>"期内已输入错误。", "KR"=>"기간이 잘못 입력되었습니다.", "EN" => "An invalid period was entered." ),
	"wrongdatatranstext"=>array("JP"=>"0","CN"=>"", "KR"=>"잘못된 전달값입니다.", "EN" => "" ),
	"HaveNoPerm"=>array("JP"=>"0","CN"=>"", "KR"=>"잘못된 접근 입니다. 관리자에게 문의하세요.", "EN" =>"" ), 
	"nodeletedept"=>array("JP"=>"0","CN"=>"", "KR"=>"하위부서가 있어 삭제할 수 없습니다.", "EN" =>"" ), 
	"nodeletedeptemp"=>array("JP"=>"0","CN"=>"", "KR"=>"소속 직원이 있어 부서를 삭제할 수 없습니다.", "EN" => "" ), 
	"nodeletecode"=>array("JP"=>"0","CN"=>"", "KR"=>"하위코드가 있어 삭제할 수 없습니다.", "EN" => "" ), 
	"nodeleteorgemp"=>array("JP"=>"0","CN"=>"", "KR"=>"기관소속 직원이 있어 삭제할 수 없습니다.", "EN" => "" ),
	"nodeleteorgdept"=>array("JP"=>"0","CN"=>"", "KR"=>"기관소속 부서가 있어 삭제할 수 없습니다.", "EN" => "" ),
  "nodata"=>array("JP"=>"0","CN"=>"", "KR"=>"데이터가 없습니다.", "EN" => "" ), 
  "novcsdata"=>array("JP"=>"0","CN"=>"", "KR"=>"점검결과가 없습니다.", "EN"=> "" ), 
  "notfoundlogininfotext"=>array("CN"=>"登录信息不匹配", "KR"=>"사용자 정보가 일치하지 않습니다.", "EN" => "User information does not match." ),
	"alreadycheckindevicetext"=>array("JP"=>"0","CN"=>"", "KR"=>"이미 반입처리된 장비입니다.", "EN" =>"" ), 
	"checkinavailabledateovertext"=>array("JP"=>"0","CN"=>"", "KR"=>"반입 가능한 날짜가 경과하였습니다.", "EN" => "" ), 
	"checkinerrortext"=>array("JP"=>"0","CN"=>"", "KR"=>"반입처리중 오류가 발생하였습니다.", "EN" => "" ), 
	"checkouterrortext"=>array("JP"=>"0","CN"=>"","KR"=>"반출처리중 오류가 발생하였습니다.", "EN" => "" ), 
	"nouserpc"=>array("JP"=>"0","CN"=>"","KR"=>"등록된 노트북이 없습니다.", "EN" => "" ), 
	"existedempno"=>array("JP"=>"0","CN"=>"","KR"=>"이미 존재하는 아이디입니다.", "EN" => "" ), 
	"existedorgid"=>array("JP"=>"0","CN"=>"","KR"=>"이미 존재하는 기관코드입니다.", "EN" => "" ), 
	"accessdenied"=>array("JP"=>"0","CN"=>"","KR"=>"접근권한이 없습니다.", "EN" => "" ), 
	"sendotpcodetext"=>array("JP"=>"0","CN"=>"","KR"=>"2단계 인증 알림이 발송되었습니다.", "EN" => "" ),
	"inputotpcodetext"=>array("JP"=>"0","CN"=>"", "KR"=>"OTP 인증번호를 입력해 주세요.", "EN" => "" ),
	"incorrectotpcodetext"=>array("JP"=>"0","CN"=>"", "KR"=>"인증번호가 올바르지 않습니다.", "EN" => ""), 
	"loginauthenticationnumbersmstext"=>array("JP"=>"0","CN"=>"", "KR"=>"로그인 인증번호는 {#} 입니다..", "EN" => "" ), 
	"remainingtimetext"=>array("JP"=>"0","CN"=>"", "KR"=>"남은시간", "EN" => ""), 
	"login"=>array("JP"=>"0","CN"=>"登录", "KR"=>"로그인", "EN" => "login" ),
	"signingin"=>array("JP"=>"0","CN"=>"", "KR"=>"로그인 중", "EN" => "" ),
	"logout"=>array("JP"=>"0","CN"=>"退出", "KR"=>"로그아웃", "EN" => "Logout" ),
	"alltext"=>array("JP"=>"0","CN"=>"", "KR"=>"전체", "EN" => "ALL" ),
	"laptoptext"=>array("JP"=>"0","CN"=>"", "KR"=>"노트북", "EN" => "ALL" ),
	"etctext"=>array("JP"=>"Etc","CN"=>"", "KR"=>"기타", "EN" => "Etc." ),
	"m_home"=>array("JP"=>"0","CN"=>"", "KR"=>"처음으로", "EN" => "ALL" ),
	"access_control"=>array("JP"=>"0","CN"=>"", "KR"=>"출입 관리", "EN" => "ALL" ),
	"access_control_theme"=>array("JP"=>"0","CN"=>"", "KR"=>"출입관리", "EN" => "ALL" ),
	"access_info_theme"=>array("JP"=>"0","CN"=>"", "KR"=>"출입정보 상세", "EN" => "ALL" ),
	"ent_exit_status_theme"=>array("JP"=>"0","CN"=>"", "KR"=>"출입 현황", "EN" => "ALL" ),
	"parking_ticket_payment"=>array("JP"=>"0","CN"=>"", "KR"=>"주차권 지급", "EN" => "ALL" ),
	"External_training"=>array("JP"=>"0","CN"=>"", "KR"=>"외부인력 정보교육", "EN" => "ALL" ),
	"External_training_details"=>array("JP"=>"0","CN"=>"", "KR"=>"외부인력 정보교육 상세", "EN" => "ALL" ),
	"rental_goods"=>array("JP"=>"0","CN"=>"", "KR"=>"물품 대여", "EN" => "ALL" ),
	"rental_deatils"=>array("JP"=>"0","CN"=>"", "KR"=>"물품 대여내역", "EN" => "ALL" ),
	"m_info"=>array("JP"=>"0","CN"=>"", "KR"=>"내 정보", "EN" => "ALL" ),
	"m_user"=>array("JP"=>"0","CN"=>"", "KR"=>"사용자", "EN" => "ALL" ),
	"m_visitor"=>array("JP"=>"0","CN"=>"", "KR"=>"방문객", "EN" => "ALL" ),
	"m_result"=>array("JP"=>"0","CN"=>"", "KR"=>"점검결과", "EN" => "ALL" ),
	"m_statistics"=>array("JP"=>"0","CN"=>"", "KR"=>"조회/통계", "EN" => "ALL" ),
	"m_manage"=>array("JP"=>"0","CN"=>"", "KR"=>"운영관리", "EN" => "ALL" ),
	"carry_in_status"=>array("JP"=>"0","CN"=>"", "KR"=>"반입여부", "EN" => "Carry-in status" ),
	"configtext"=>array("CN"=>"设置", "KR"=>"환경설정", "EN" => "Settings" ),
	"server_transfer_status"=>array("CN"=>"设置", "KR"=>"서버전송여부", "EN" => "Server transfer status" ),
	"server_transfer_status_text"=>array("CN"=>"设置", "KR"=>"서버전송", "EN" => "Server transfer status" ),
	"filesignature"=>array("CN"=>"签名文件", "KR"=>"파일시그니처", "EN" => "File signature" ),
	"registerdescviewnntext"=>array("CN"=>"按登入顺序查看", "KR"=>"등록순으로보기", "EN" => "View by registration date" ),
	"fileextdescviewnntext"=>array("CN"=>"按扩展名顺序查看", "KR"=>"확장자순으로보기", "EN" => "View by extension" ),
	"searchtargetnntext"=>array("CN"=>"搜索对象", "KR"=>"검색대상", "EN" => "Search target" ),
	"filesignaturelistnntext"=>array("CN"=>"文件签名目录", "KR"=>"파일시그니처목록", "EN" => "File signature list" ),
	"signaturestat"=>array("CN"=>"分析Signature", "KR"=>"시그니처분석", "EN" => "Signature Anal.." ),
	"BLACKLIST"=>array("CN"=>"BLACKLIST", "KR"=>"BLACKLIST", "EN" => "BLACKLIST" ),
	"alllistview"=>array("CN"=>"查看全部", "KR"=>"모두보기", "EN" => "Show all" ),
	"file_ext"=>array("CN"=>"扩展名", "KR"=>"확장자", "EN" => "Extension" ),
	"totallist"=>array("CN"=>"全部", "KR"=>"전체", "EN" => "All" ),
	"file_id"=>array("CN"=>"File Id", "KR"=>"File Id", "EN" => "File Id" ),
	"id_name"=>array("CN"=>"ID Name", "KR"=>"ID Name", "EN" => "ID Name" ),
	"inspection_date"=>array("CN"=>"ID Name", "KR"=>"검사일자", "EN" => "Inspection date" ),
	"useyesnntext"=>array("CN"=>"使用", "KR"=>"사용함", "EN" => "Enabled" ),
	"signaturemappinginfonntext"=>array("CN"=>" signatur比较信息", "KR"=>"시그니처맵핑정보", "EN" => "Signature mapping Info." ),
	"usenonntext"=>array("CN"=>"不要使用", "KR"=>"사용안함", "EN" => "Disabled" ),
	"fileidnntext"=>array("CN"=>"文件编号", "KR"=>"파일ID", "EN" => "File ID" ),
	"Md5"=>array("CN"=>"文件编号", "KR"=>"Md5", "EN" => "Md5" ),
	"signaturemapping"=>array("CN"=>"signatur比较", "KR"=>"시그니처맵핑", "EN" => "Signature mapping" ),
	"useyesnonntext"=>array("CN"=>"是否使用", "KR"=>"사용여부", "EN" => "Enable/Disable option" ),
	"m_my_info"=>array("JP"=>"0","CN"=>"", "KR"=>"나의 정보", "EN" => "ALL" ),
	"m_visitor_info"=>array("JP"=>"0","CN"=>"", "KR"=>"방문객 정보", "EN" => "ALL" ),
	"m_visitor_info.edit"=>array("JP"=>"0","CN"=>"", "KR"=>"방문객 정보 수정", "EN" => "ALL" ),
	"m_result_pc"=>array("JP"=>"0","CN"=>"", "KR"=>"노트북 점검결과", "EN" => "ALL" ),
	"m_result_storage"=>array("JP"=>"0","CN"=>"", "KR"=>"저장매체 점검결과", "EN" => "ALL" ),
	"m_com_info"=>array("JP"=>"0","CN"=>"", "KR"=>"회사 정보", "EN" => "ALL" ),
	"m_com_info.edit"=>array("JP"=>"0","CN"=>"", "KR"=>"회사 정보 수정", "EN" => "ALL" ),
	"m_statistics_result"=>array("JP"=>"0","CN"=>"", "KR"=>"점검현황", "EN" => "ALL" ),
	"m_statistics_result_pc"=>array("JP"=>"0","CN"=>"", "KR"=>"노트북 점검현황", "EN" => "ALL" ),
	"m_statistics_result_storage"=>array("JP"=>"0","CN"=>"", "KR"=>"저장매체 점검현황", "EN" => "ALL" ),
	"m_statistics_result_company"=>array("JP"=>"0","CN"=>"", "KR"=>"업체별 점검현황", "EN" => "ALL" ),
	"m_statistics_pc"=>array("JP"=>"0","CN"=>"", "KR"=>"방문객 노트북 분석", "EN" => "ALL" ),
	"m_report"=>array("JP"=>"0","CN"=>"", "KR"=>"리포트", "EN" => "ALL" ),
	"m_query_editor"=>array("JP"=>"","CN"=>"", "KR"=>"커스텀 쿼리", "EN" => "Query Editor" ),
	"file_inspection_details"=>array("JP"=>"0","CN"=>"", "KR"=>"파일검사내역", "EN" => "File inspection details" ),
	"m_manage_organization"=>array("JP"=>"0","CN"=>"", "KR"=>"조직관리", "EN" => "ALL" ),
	"m_manage_employee"=>array("JP"=>"0","CN"=>"", "KR"=>"직원관리", "EN" => "ALL" ),
	"m_manage_department"=>array("JP"=>"0","CN"=>"", "KR"=>"부서관리", "EN" => "ALL" ),
	"m_manage_scan_center"=>array("JP"=>"0","CN"=>"", "KR"=>"검사장관리", "EN" => "ALL" ),
	"m_manage_group"=>array("JP"=>"0","CN"=>"", "KR"=>"그룹관리", "EN" => "ALL" ),
	"m_manage_position"=>array("JP"=>"0","CN"=>"", "KR"=>"직위/직책관리", "EN" => "ALL" ),
	"m_manage_policy"=>array("JP"=>"0","CN"=>"", "KR"=>"정책설정", "EN" => "ALL" ),
	"m_manage_policy_weakness"=>array("JP"=>"0","CN"=>"", "KR"=>"윈도우즈 취약점 검사 항목설정", "EN" =>"ALL" ), 
	"m_manage_vaccine"=>array("JP"=>"0","CN"=>"", "KR"=>"백신관리", "EN" => "ALL" ),
	"inputpwdpleasenntext"=>array("JP"=>"Type in the password.", "CN"=>"请输入密码。", "KR"=>"비밀번호를 입력하세요.", "EN" => "Type in the password." ),
	"m_manage_appupdate"=>array("JP"=>"0","CN"=>"", "KR"=>"App업데이트관리", "EN" => "ALL" ),
	"m_manage_accessip"=>array("JP"=>"0","CN"=>"", "KR"=>"접속IP관리", "EN" => "Access IP Mgt" ),
	"inputvalidate"=>array("JP"=>"", "CN"=>"", "KR"=>"fill the all blanks", "EN" => "fill the all blanks" ),
	"file_id_validate"=>array("JP"=>"", "CN"=>"", "KR"=>"파일ID를 입력하세요.", "EN" => "fill the all blanks" ),
	"file_sig_validate"=>array("JP"=>"", "CN"=>"", "KR"=>"파일시그니처 입력하세요.", "EN" => "fill the all blanks" ),
	"inclusionnntext"=>array("CN"=>"包含", "KR"=>"포함", "EN" => "Included" ),
	"exclusionnntext"=>array("CN"=>"除外", "KR"=>"제외", "EN" => "Excluded" ),
	"createdatetext"=>array("CN"=>"创作时间", "KR"=>"생성일자", "EN" => "Date created" ),
	"deletedeletetext"=>array("CN"=>"删除", "KR"=>"삭제", "EN" => "Delete" ),
	"longtimeunusedcanceltext"=>array("JP"=>"", "CN"=>"长期断线取消", "KR"=>"장기미접속 해제", "EN" => "Long-term disconnection cancellation" ),
	"loginattemptresettext"=>array("JP"=>"Reset the number of login attempts","CN"=>"重置登录尝试次数", "KR"=>"로그인시도횟수 초기화", "EN" => "Reset the number of login attempts" ),
	"loginlock"=>array("JP"=>"Account lock", "CN"=>"账户锁定", "KR"=>"계정잠금", "EN" => "Account lock" ),
	"loginidstatus"=>array("JP"=>"Login status", "CN"=>"登录状态", "KR"=>"접속상태", "EN" => "Login status" ),
	"loginstatus"=>array("JP"=>"Login success", "CN"=>"登录成功", "KR"=>"접속여부", "EN" => "Login success" ),
	"idtext"=>array("JP"=>"ID", "CN"=>"用户名", "KR"=>"아이디", "EN" => "ID"  ),
	"timestext"=>array("JP"=>" Times", "CN"=>" 次", "KR"=>" 회", "EN" => " Times" ),
	"normal"=>array("JP"=>"OK", "CN"=>"好的", "KR"=>"정상", "EN" => "OK" ),
	"loginattemptexceed"=>array("JP"=>"Exceeded login attempts", "CN"=>"超过登录尝试次数", "KR"=>"로그인시도횟수초과", "EN" => "Exceeded login attempts" ),
	"longtimedisconnected"=>array("JP"=>"Long-term disconnection", "CN"=>"长期断线", "KR"=>"장기미접속", "EN" => "Long-term disconnection" ),
	"loginattemptcntexceed"=>array("JP"=>"","CN"=>"超过了可能的登录尝试次数(#次)。请与您的管理员联系.","KR"=>"로그인 시도 가능횟수를 초과하였습니다(#회). 관리자에게 문의해 주세요.","EN"=>"The number of possible login attempts exceeded(#times). Please contact your administrator."),
	"reset_yn"=>array("JP"=>"Reset_yn", "CN"=>"访问权限ID", "KR"=>"Reset_yn","EN" => "Reset_yn" ),
	"attemptlogin"=>array("JP"=>"0","CN"=>"", "KR"=>"접속 시도", "EN" => "Attempt Login" ),
	"loginattemptlimittext"=>array("JP"=>"Limit the number of login attempts","CN"=>"限制登录尝试次数", "KR"=>"로그인시도횟수 제한", "EN" => "Limit the number of login attempts" ),
	"loginiplimittext"=>array("JP"=>"Loginable IP Restrictions","CN"=>"可登录的 IP 限制", "KR"=>"접속가능한 IP 제한", "EN" => "Loginable IP Restrictions" ),
	"etcpolicy"=>array("JP"=>"Etc policy", "CN"=>"等政策", "KR"=>"기타 정책", "EN" => "Etc policy" ),
	"btnipregist"=>array("JP"=>"IP registration", "CN"=>"登录IP", "KR"=>"IP 등록", "EN" => "IP registration" ),
	"searchkeywordselecttext"=>array("JP"=>"Select search keyword", "CN"=>"选择搜索关键词", "KR"=>"검색키워드 선택", "EN" => "Select search keyword" ),
	"select_search_item"=>array("JP"=>"Select search keyword", "CN"=>"", "KR"=>"검색항목선택", "EN" => "Select search keyword" ),
	"idornametext"=>array("JP"=>"ID or name", "CN"=>"用户名或姓名", "KR"=>"아이디또는이름", "EN" => "ID or name" ),
	"registertext"=>array("JP"=>"Registerer", "CN"=>"登录者", "KR"=>"등록자", "EN" => "Registerer" ),
	"register"=>array("JP"=>"Register", "CN"=>"등록하기", "KR"=>"등록하기", "EN" => "Register" ),
	"searchtargetinnntext"=>array("CN"=>"包括搜索对象", "KR"=>"검색대상포함", "EN" => "Search target included" ),
	"signatureinnntext"=>array("CN"=>"包括签名与否", "KR"=>"시그니처여부포함", "EN" => "Signature option included" ),
	"signatureoutnntext"=>array("CN"=>"不包括签名与否，", "KR"=>"시그니처여부제외", "EN" => "Signature option excluded" ),
	"searchtargetoutnntext"=>array("CN"=>"不包括搜索对象", "KR"=>"검색대상제외", "EN" => "Search target excluded" ),
	"registdatetext"=>array("JP"=>"Date registered", "CN"=>"注册日期", "KR"=>"등록일자", "EN" => "Date registered"  ),
	"noneresult"=>array("JP"=>"No search results found.", "CN"=>"没有找到结果。", "KR"=>"찾은 결과가 없습니다.", "EN" => "No search results found." ),
	"alltext"=>array("JP"=>"All", "CN"=>"全部", "KR"=>"전체", "EN" => "ALL" ),
	"m_manage_code"=>array("JP"=>"0","CN"=>"", "KR"=>"코드관리", "EN" => "ALL" ),
	"ipaddresstext"=>array("JP"=>"IP Address", "CN"=>"IP Address", "KR"=>"IP주소", "EN" => "IP Address"), 
	"accesspermitid"=>array("JP"=>"Access permission ID", "CN"=>"访问权限ID", "KR"=>"접속허용 ID","EN" => 
	"Access permission ID" ), 
	"memotext"=> array("JP"=>"Memo", "CN"=>"备忘录", "KR"=>"비고","EN" => "Note" ), 
	"inputmemotext"=> array("JP"=>"", "CN"=>"", "KR"=>"비고를 입력하세요","EN" => "" ), 
	"m_manage_admin"=>array("JP"=>"0","CN"=>"", "KR"=>"관리자정보", "EN" => "ALL" ),
	"m_manage_admin.regist"=>array("JP"=>"0","CN"=>"", "KR"=>"관리자등록", "EN" => "ALL" ),
	"m_manage_admin.info"=>array("JP"=>"0","CN"=>"", "KR"=>"관리자정보", "EN" => "ALL" ),
	"m_manage_adminloginlog"=>array("JP"=>"0","CN"=>"", "KR"=>"관리자접속내역", "EN" => "ALL" ),
	"m_manage_checkinscanlog"=>array("JP"=>"0","CN"=>"", "KR"=>"바코드스캔로그", "EN" => "ALL" ),
	"m_manage_notice"=>array("JP"=>"0","CN"=>"", "KR"=>"공지시항", "EN" => "ALL" ),
	"m_manage_faq"=>array("JP"=>"0","CN"=>"", "KR"=>"FAQ", "EN" => "ALL" ),
	"nopolicymsg"=>array("JP"=>"0","CN"=>"", "KR"=>"현재 설정된 정책이 없습니다.", "EN" => "" ),
	"adminpasswordchagetermtext"=>array("JP"=>"0","CN"=>"", "KR"=>"관리자 비밀번호 변경주기", "EN" => ""), 
	"dataconnectionyntext"=>array("JP"=>"0","CN"=>"", "KR"=>"데이터 연동여부", "EN" => "" ),
	"checkinavailabledatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"반입가능 유효기간", "EN" => "" ),
	"windowsupdatevaliditytext"=>array("JP"=>"0","CN"=>"", "KR"=>"윈도우즈 업데이트 유효기간", "EN" =>"" ), 
	"windowsupdateyntext"=>array("JP"=>"0","CN"=>"", "KR"=>"윈도우즈 업데이트 적용", "EN" => "" ),
	"windowweaknesscheckyntext"=>array("JP"=>"0","CN"=>"", "KR"=>"윈도우즈 취약점검사 적용", "EN" => ""), 
	"vaccinecheckyntext"=>array("JP"=>"0","CN"=>"", "KR"=>"백신검사 적용", "EN" => "" ),
	"vaccinescantypetext"=>array("JP"=>"0","CN"=>"", "KR"=>"백신 검사방식", "EN" => "" ),
	"vaccineupdatevaliditytext"=>array("JP"=>"0","CN"=>"", "KR"=>"백신 업데이트 유효기간", "EN" => "" ),
	"screenlockyntext"=>array("JP"=>"0","CN"=>"", "KR"=>"화면잠금여부", "EN" => "" ),
	"screenlockguidetext"=>array("JP"=>"0","CN"=>"", "KR"=>"화면잠금 안내문구", "EN" => "" ),
	"webtypetext"=>array("JP"=>"0","CN"=>"", "KR"=>"WEB 방식", "EN" => "" ),
	"webserveraddrtext"=>array("JP"=>"0","CN"=>"", "KR"=>"WEB 서버주소", "EN" => "" ),
	"porttext"=>array("JP"=>"0","CN"=>"", "KR"=>"포트", "EN" => "" ),
	"webporttext"=>array("JP"=>"0","CN"=>"", "KR"=>"WEB 포트", "EN" => "" ),
	"ftptypetext"=>array("JP"=>"0","CN"=>"", "KR"=>"FTP 종류", "EN" => "" ),
	"ftpserveraddrtext"=>array("JP"=>"0","CN"=>"", "KR"=>"FTP 서버주소", "EN" => "" ),
	"ftpporttext"=>array("JP"=>"0","CN"=>"", "KR"=>"FTP 포트", "EN" => "" ),
	"mailtypetext"=>array("JP"=>"0","CN"=>"", "KR"=>"메일 종류", "EN" => "" ),
	"mailserveraddrtext"=>array("JP"=>"0","CN"=>"", "KR"=>"메일 서버주소", "EN" => "" ),
	"mailporttext"=>array("JP"=>"0","CN"=>"", "KR"=>"메일 포트", "EN" => "" ),
	"mailsendadminidtext"=>array("JP"=>"0","CN"=>"", "KR"=>"메일 전송 관리자아이디", "EN" => "" ),
	"mailsendadminpwdtext"=>array("JP"=>"0","CN"=>"", "KR"=>"메일 전송 관리자비밀번호", "EN" => "" ),
	"smstypetext"=>array("JP"=>"0","CN"=>"", "KR"=>"SMS 방식", "EN" => "" ),
	"smsserveraddrtext"=>array("JP"=>"0","CN"=>"", "KR"=>"SMS 서버주소", "EN" => "" ),
	"smsporttext"=>array("JP"=>"0","CN"=>"", "KR"=>"SMS 포트", "EN" => "" ),
	"smssendidtext"=>array("JP"=>"0","CN"=>"", "KR"=>"SMS 전송아이디", "EN" => "" ),
	"smssendpwdtext"=>array("JP"=>"0","CN"=>"", "KR"=>"SMS 전송비밀번호", "EN" => "" ),
	"smsdbtext"=>array("JP"=>"0","CN"=>"", "KR"=>"SMS DB", "EN" => "" ),
	"smsdbtabletext"=>array("JP"=>"0","CN"=>"", "KR"=>"SMS DB TABLE", "EN" => "" ),
	"smssendweburltext"=>array("JP"=>"0","CN"=>"", "KR"=>"SMS 전송 WEB URL", "EN" => "" ),
	"smssendtelnotext"=>array("JP"=>"0","CN"=>"", "KR"=>"SMS 발신번호", "EN" => "" ),
	"programupdateservertext"=>array("JP"=>"0","CN"=>"", "KR"=>"프로그램 업데이트 서버", "EN" => "" ),
	"programapiservertext"=>array("JP"=>"0","CN"=>"", "KR"=>"프로그램 API 서버", "EN" => "" ),
	"otpuseyntext"=>array("JP"=>"0","CN"=>"", "KR"=>"OTP 사용여부", "EN" => "" ),
	"weaknesstext"=>array("JP"=>"0","CN"=>"", "KR"=>"취약점", "EN" => "" ),
	"weaknessshorttext"=>array("JP"=>"0","CN"=>"", "KR"=>"취약", "EN" => "" ),
	"virusshorttext"=>array("JP"=>"","CN"=>"", "KR"=>"악성", "EN" => "" ),
	"safetytext"=>array("JP"=>"0","CN"=>"", "KR"=>"안전", "EN" => "Safe" ),
	"solutionstext"=>array("JP"=>"0","CN"=>"", "KR"=>"해결책", "EN" => "" ),
	"resultchoosetext"=>array("JP"=>"0","CN"=>"", "KR"=>"결과선택", "EN" => "" ),
	"detailviewtext"=>array("JP"=>"0","CN"=>"", "KR"=>"상세내역", "EN" => "" ),
	"usersearchtext"=>array("JP"=>"0","CN"=>"", "KR"=>"검색", "EN" => "" ),
	"userdetailsearchtext"=>array("JP"=>"0","CN"=>"", "KR"=>"상세검색", "EN" => "" ),
	"organselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"기관 선택", "EN" => "" ),
	"searchkeywordselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"검색키워드 선택", "EN" => "" ),
	"deptselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"부서 선택", "EN" => "" ),
	"superdeptselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"상위부서 선택", "EN" => "" ),
	"empselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"사원 선택", "EN" => "" ),
	"pcstatusselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"노트북상태 선택", "EN" => "" ),
	"userchangeselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용자변경 선택", "EN" => "" ),
	"gubuntext"=>array("JP"=>"0","CN"=>"", "KR"=>"구분", "EN" => "" ),
	"gubunselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"구분 선택", "EN" => "" ),
	"filetypeselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"파일유형 선택", "EN" => "" ),
	"dategubunselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"날짜구분 선택", "EN" => "" ),
	"deptchiefselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"부서장 선택", "EN" => "" ),
	"useynselecttext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용여부 선택", "EN" => "" ),
	"useperiodtext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용기간", "EN" => "" ),
	"loginperiodtext"=>array("JP"=>"0","CN"=>"", "KR"=>"접속기간", "EN" => "" ),
	"entry_date"=>array("JP"=>"0","CN"=>"", "KR"=>"출입 일자", "EN" => "" ),
	"scanperiodtext"=>array("JP"=>"0","CN"=>"", "KR"=>"스캔기간", "EN" => "" ),
	"file_inspection_period"=>array("JP"=>"0","CN"=>"", "KR"=>"파일검사기간", "EN" => "File inspection period" ),
	"barcodescantext"=>array("JP"=>"0","CN"=>"", "KR"=>"바코드 스캔", "EN" => "" ),
	"scanresulttext"=>array("JP"=>"0","CN"=>"", "KR"=>"바코드 스캔결과", "EN" => "" ),
	"accessdatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"처리일자", "EN" => "" ),
	"accessusertext"=>array("JP"=>"0","CN"=>"", "KR"=>"처리자", "EN" => "" ),
	"barcodescandatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"확인일자", "EN" => "" ),
	"barcodescanemptext"=>array("JP"=>"0","CN"=>"", "KR"=>"확인자", "EN" => "" ),
	"numtext"=>array("JP"=>"0","CN"=>"", "KR"=>"번호", "EN" => "number" ),
	"empnotext"=>array("JP"=>"0","CN"=>"", "KR"=>"아이디", "EN" => "" ),
	"empnametext"=>array("JP"=>"0","CN"=>"", "KR"=>"임직원명", "EN" => "" ),
	"depttext"=>array("JP"=>"0","CN"=>"", "KR"=>"부서", "EN" => "" ),
	"visitor_name"=>array("JP"=>"0","CN"=>"", "KR"=>"방문자명", "EN" => "" ),
	"visitor_name_en"=>array("JP"=>"0","CN"=>"", "KR"=>"방문자 영문명", "EN" => "" ),
	"entry_time"=>array("JP"=>"0","CN"=>"", "KR"=>"출입일시", "EN" => "" ),
	"jobgradetext"=>array("JP"=>"0","CN"=>"", "KR"=>"직급", "EN" => "" ),
	"jobdutytext"=>array("JP"=>"0","CN"=>"", "KR"=>"직책", "EN" => "" ),
	"jobpostext"=>array("JP"=>"0","CN"=>"", "KR"=>"직위", "EN" => "" ),
	"gradetext"=>array("JP"=>"0","CN"=>"", "KR"=>"등급", "EN" => "" ),
	"uselangtext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용언어", "EN" => "" ),
	"securityleveltext"=>array("JP"=>"0","CN"=>"", "KR"=>"보안등급", "EN" => "" ),
	"adminleveltext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용자등급", "EN" => "" ),
	"userleveltext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용자등급", "EN" => "" ),
	"gubuntext"=>array("JP"=>"0","CN"=>"", "KR"=>"구분", "EN" => "Classification" ),
	"titletext"=>array("JP"=>"0","CN"=>"", "KR"=>"제목", "EN" => "Title" ),
	"titlencontentstext"=>array("JP"=>"0","CN"=>"", "KR"=>"제목+내용", "EN" => "" ),
	"attachfiletext"=>array("JP"=>"0","CN"=>"", "KR"=>"첨부파일", "EN" => "" ),
	"registertext"=>array("JP"=>"0","CN"=>"", "KR"=>"등록자", "EN" => "" ),
	"registerdatetext"=>array("JP"=>"0","CN"=>"注册日期", "KR"=>"등록일", "EN" => "Date registered" ),
	"firstregistdatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"최초등록일", "EN" => "Date registered" ),
	"lastregistdatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"최종등록일", "EN" => "Date registered" ),
	"updatertext"=>array("JP"=>"0","CN"=>"", "KR"=>"수정자", "EN" => "" ),
	"updatedatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"수정일", "EN" => "" ),
	"updated_date_text_value"=>array("JP"=>"0","CN"=>"", "KR"=>"수정일자", "EN" => "" ),
	"usertext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용자", "EN" => "" ),
	"visitortext"=>array("JP"=>"0","CN"=>"", "KR"=>"방문자", "EN" => "" ),
	"generalusertext"=>array("JP"=>"0","CN"=>"", "KR"=>"일반사용자", "EN" => "" ),
	"serialnumbertext"=>array("JP"=>"0","CN"=>"", "KR"=>"Serial No.", "EN" => "" ),
	"windowsdirectorytext"=>array("JP"=>"0","CN"=>"", "KR"=>"Windows Dir", "EN" => "" ),
	"ostext"=>array("JP"=>"0","CN"=>"", "KR"=>"운영체제", "EN" => "" ),
	"osndevicetext"=>array("JP"=>"0","CN"=>"", "KR"=>"Device 또는 운영체제", "EN" => "" ),
	"devicetext"=>array("JP"=>"Device","CN"=>"", "KR"=>"Device", "EN" => "Device" ),
	"windowsdirtext"=>array("JP"=>"0","CN"=>"", "KR"=>"Windows Dir", "EN" => "" ),
	"cputext"=>array("JP"=>"0","CN"=>"", "KR"=>"CPU", "EN" => "" ),
	"macaddresstext"=>array("JP"=>"0","CN"=>"", "KR"=>"Mac Address", "EN" => "" ),
	"manufacturertext"=>array("JP"=>"0","CN"=>"", "KR"=>"제조사", "EN" => "" ),
	"modeltext"=>array("JP"=>"0","CN"=>"", "KR"=>"모델", "EN" => "" ),
	"ramtext"=>array("JP"=>"0","CN"=>"", "KR"=>"RAM", "EN" => "" ),
	"statustext"=>array("JP"=>"0","CN"=>"", "KR"=>"상태", "EN" => "" ),
	"currentstatustext"=>array("JP"=>"0","CN"=>"", "KR"=>"현재상태", "EN" => "" ),
	"workplacetext"=>array("JP"=>"0","CN"=>"", "KR"=>"근무지", "EN" => "" ),
	"workyntext"=>array("JP"=>"0","CN"=>"", "KR"=>"근무여부", "EN" => "" ),
	"workyestext"=>array("JP"=>"0","CN"=>"", "KR"=>"근무함", "EN" => "" ),
	"worknotext"=>array("JP"=>"0","CN"=>"", "KR"=>"근무안함", "EN" => "" ),
	"emailtext"=>array("JP"=>"0","CN"=>"", "KR"=>"E-mail", "EN" => "" ),
	"passwordtext"=>array("JP"=>"0","CN"=>"", "KR"=>"비밀번호", "EN" => "" ),
	"passwordconfirmtext"=>array("JP"=>"0","CN"=>"", "KR"=>"비밀번호 확인", "EN" => "" ),
	"newpasswordtext"=>array("JP"=>"0","CN"=>"", "KR"=>"새 비밀번호", "EN" => "" ),
	"newpasswordconfirmtext"=>array("JP"=>"0","CN"=>"", "KR"=>"새 비밀번호 확인", "EN" => "" ),
	"contactphonetext"=>array("JP"=>"0","CN"=>"", "KR"=>"연락처", "EN" => "" ),
	"date_visit"=>array("JP"=>"0","CN"=>"", "KR"=>"방문일시", "EN" => "" ),
	"managetext"=>array("JP"=>"0","CN"=>"", "KR"=>"관리", "EN" => "" ),
	"resettext"=>array("JP"=>"0","CN"=>"", "KR"=>"재설정", "EN" => "" ),
	"koreantext"=>array("JP"=>"0","CN"=>"", "KR"=>"한글", "EN" => "" ),
	"englishtext"=>array("JP"=>"0","CN"=>"", "KR"=>"영어", "EN" => "" ),
	"japanesetext"=>array("JP"=>"0","CN"=>"", "KR"=>"일본어", "EN" => "" ),
	"chinesetext"=>array("JP"=>"Chinese", "CN"=>"汉语", "KR"=>"중국어", "EN" => "Chinese" ),
	"userinfotext"=>array("JP"=>"0","CN"=>"用户信息", "KR"=>"사용자정보", "EN" => "User Info." ),
	"visitorinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"방문객정보", "EN" => "Visitor Info." ),
	"employeeinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"사원정보", "EN" => "" ),
	"usagetext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용현황", "EN" => "" ),
	"checkinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"점검정보", "EN" => "" ),
	"pcinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"노트북정보", "EN" => "" ),
	"diskinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"디스크정보", "EN" => "" ),
	"programinstalledinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"프로그램설치정보", "EN" => "" ),
	"securityweaknesstext"=>array("JP"=>"0","CN"=>"", "KR"=>"보안취약점", "EN" => "" ),
	"windowupdatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"윈도우즈업데이트", "EN" => "" ),
	"windowversiontext"=>array("JP"=>"0","CN"=>"", "KR"=>"윈도우즈 버전", "EN" => "" ),
	"vaccineruninfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"백신실행정보", "EN" => "" ),
	"runinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"실행정보", "EN" => "" ),
	"runresulttext"=>array("JP"=>"0","CN"=>"", "KR"=>"실행결과", "EN" => "" ),
	"iplogtext"=>array("JP"=>"0","CN"=>"", "KR"=>"IP LOG", "EN" => "" ),
	"hddserialnumbertext"=>array("JP"=>"0","CN"=>"", "KR"=>"HDD S/N", "EN" => "" ),
	"boardserialnumbertext"=>array("JP"=>"0","CN"=>"", "KR"=>"Board S/N", "EN" => "" ),
	"useraccounttext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용자계정", "EN" => "" ),
	"bootdevicetext"=>array("JP"=>"0","CN"=>"", "KR"=>"Boot Device", "EN" => "" ),
	"userkeytext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용자 키", "EN" => "" ),
	"ldisktext"=>array("JP"=>"0","CN"=>"", "KR"=>"논리 디스크", "EN" => "" ),
	"pdisktext"=>array("JP"=>"0","CN"=>"", "KR"=>"물리 디스크", "EN" => "" ),
	"macaddrtext"=>array("JP"=>"0","CN"=>"", "KR"=>"MAC 주소", "EN" => "" ),
	"programnametext"=>array("JP"=>"0","CN"=>"", "KR"=>"프로그램명", "EN" => "" ),
	"versiontext"=>array("JP"=>"0","CN"=>"", "KR"=>"버전", "EN" => "" ),
	"installdatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"설치일", "EN" => "" ),
	"contentstext"=>array("JP"=>"0","CN"=>"内容", "KR"=>"내용", "EN" => "Contents" ),
	"companycodetext"=>array("JP"=>"0","CN"=>"", "KR"=>"회사코드", "EN" => "" ),
	"companynametext"=>array("JP"=>"0","CN"=>"", "KR"=>"회사명", "EN" => "" ),
	"deptnametext"=>array("JP"=>"0","CN"=>"", "KR"=>"부서명", "EN" => "" ),
	"deptchieftext"=>array("JP"=>"0","CN"=>"", "KR"=>"부서장", "EN" => "" ),
	"usercompanyinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"업체정보", "EN" => "" ),
	"usercompanytext"=>array("JP"=>"0","CN"=>"", "KR"=>"회사", "EN" => "" ),
	"usercompanynametext"=>array("JP"=>"0","CN"=>"", "KR"=>"회사명", "EN" => "" ),
	"usercompanycodetext"=>array("JP"=>"0","CN"=>"", "KR"=>"업체코드", "EN" => "" ),
	"usercompanychoosetext"=>array("JP"=>"0","CN"=>"", "KR"=>"회사 선택", "EN" => "" ),
	"usercompanyaddtext"=>array("JP"=>"0","CN"=>"", "KR"=>"회사 추가", "EN" => "" ),
	"managertext"=>array("JP"=>"0","CN"=>"", "KR"=>"담당자", "EN" => "" ),
	"manager_en_text"=>array("JP"=>"0","CN"=>"", "KR"=>"임직원 영문 이름", "EN" => "" ),
	"managedepartmenttext"=>array("JP"=>"0","CN"=>"", "KR"=>"담당부서", "EN" => "" ),
	"accounttext"=>array("JP"=>"0","CN"=>"", "KR"=>"계정", "EN" => "" ),
	"import_information"=>array("JP"=>"0","CN"=>"", "KR"=>"반입정보", "EN" => "" ),
	"import_data_inspection_results"=>array("JP"=>"0","CN"=>"", "KR"=>"파일반입 점검결과", "EN" => "" ),
	"ceotext"=>array("JP"=>"0","CN"=>"", "KR"=>"대표자", "EN" => "" ),
	"companyregistrationnumbertext"=>array("JP"=>"Company Registration Number","CN"=>"", "KR"=>"사업자등록번호", "EN" => "Company Registration Number" ),
	"companyindustrytext"=>array("JP"=>"Company industry","CN"=>"", "KR"=>"업종", "EN" => "Company industry" ), 
	"companycategorytext"=>array("JP"=>"Company Category","CN"=>"", "KR"=>"업태", "EN" =>"Company Category" ), 
	"companycategorytext"=>array("JP"=>"Company Category","CN"=>"", "KR"=>"업태","EN" => "Company Category" ), 
	"approvedyesnotext"=>array("JP"=>"Approval Status","CN"=>"","KR"=>"승인여부", "EN" => "Approval Status" ), 
	"approvedtext"=>array("JP"=>"Approved","CN"=>"","KR"=>"승인", "EN" => "Approved" ), 
	"unapprovedtext"=>array("JP"=>"Unapproved","CN"=>"","KR"=>"미승인", "EN" => "Unapproved" ), 
	"checkndevicegubuntext"=>array("JP"=>"","CN"=>"","KR"=>"점검/장비 구분", "EN" => "" ), 
	"registdevicelisttext"=>array("JP"=>"","CN"=>"","KR"=>"등록장비내역", "EN" => "" ), 
	"devicegubuntext"=>array("JP"=>"","CN"=>"", "KR"=>"장비구분","EN" => "" ), 
	"checkdiskcounttext"=>array("JP"=>"","CN"=>"", "KR"=>"검사매체갯수", "EN" => "" ),
	"devicegubunchoosetext"=>array("JP"=>"","CN"=>"", "KR"=>"장비구분선택", "EN" => "" ),
	"usercompanynamechoosetext"=>array("JP"=>"0","CN"=>"", "KR"=>"업체선택", "EN" => "" ),
	"devicealltext"=>array("JP"=>"","CN"=>"", "KR"=>"장비 전체", "EN" => "" ),
	"storagegubuntext"=>array("JP"=>"","CN"=>"", "KR"=>"저장매체구분", "EN" => "" ),
	"storagegubunchoosetext"=>array("JP"=>"","CN"=>"", "KR"=>"저장매체구분선택", "EN" => "" ),
	"lastcheckperiodtext"=>array("JP"=>"","CN"=>"", "KR"=>"최종점검기간", "EN" => "" ),
	"checkperiodtext"=>array("JP"=>"","CN"=>"", "KR"=>"점검기간", "EN" => "" ),
	"inperiodtext"=>array("JP"=>"","CN"=>"", "KR"=>"반입기간", "EN" => "" ),
	"outperiodtext"=>array("JP"=>"","CN"=>"", "KR"=>"반출기간", "EN" => "" ),
	"vcsprogressstatuschoosetext"=>array("JP"=>"","CN"=>"", "KR"=>"점검 진행상태를 선택하세요", "EN" =>"" ), 
	"progressstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"진행상태", "EN" => "" ),
	"storagedevicetext"=>array("JP"=>"","CN"=>"", "KR"=>"저장매체", "EN" => "" ),
	"checkdevicetext"=>array("JP"=>"","CN"=>"", "KR"=>"검사매체", "EN" => "" ),
	"lastcheckdatetext"=>array("JP"=>"","CN"=>"", "KR"=>"최종검사일", "EN" => "" ),
	"checkdatetext"=>array("JP"=>"","CN"=>"", "KR"=>"검사일", "EN" => "" ),
	"checkplacetext"=>array("JP"=>"","CN"=>"", "KR"=>"검사장소", "EN" => "" ),
	"inlimitdatetext"=>array("JP"=>"","CN"=>"", "KR"=>"반입가능기한", "EN" => "" ),
	"indatetext"=>array("JP"=>"","CN"=>"", "KR"=>"반입일", "EN" => "" ),
	"outdatetext"=>array("JP"=>"","CN"=>"", "KR"=>"반출일", "EN" => "" ),
	"checkgubuntext"=>array("JP"=>"","CN"=>"", "KR"=>"점검구분", "EN" => "" ),
	"checkgubunchoosetext"=>array("JP"=>"","CN"=>"", "KR"=>"점검구분선택", "EN" => "" ),
	"weaknessnvirustext"=>array("JP"=>"","CN"=>"", "KR"=>"취약점/악성코드", "EN" => "" ),
	"weaknessnviruslisttext"=>array("JP"=>"","CN"=>"", "KR"=>"취약점/악성코드 내역", "EN" => "" ),
	"keywordsearchtext"=>array("JP"=>"","CN"=>"", "KR"=>"키워드 검색", "EN" => "" ),
	"checkapprovaltext"=>array("JP"=>"","CN"=>"", "KR"=>"점검승인", "EN" => "" ),
	"checkapprovertext"=>array("JP"=>"","CN"=>"", "KR"=>"점검자", "EN" => "" ),
	"checkapproveddatertext"=>array("JP"=>"","CN"=>"", "KR"=>"점검승인일", "EN" => "" ),
	"needchecktext"=>array("JP"=>"","CN"=>"", "KR"=>"확인필요", "EN" => "" ),
	"confirmcompletetext"=>array("JP"=>"","CN"=>"", "KR"=>"점검완료", "EN" => "" ),
	"approvedcompletetext"=>array("JP"=>"","CN"=>"", "KR"=>"승인완료", "EN" => "" ),
	"incompletetext"=>array("JP"=>"","CN"=>"", "KR"=>"반입완료", "EN" => "" ),
	"outcompletetext"=>array("JP"=>"","CN"=>"", "KR"=>"반출완료", "EN" => "" ),
	"checkresulttext"=>array("JP"=>"0","CN"=>"", "KR"=>"점검결과", "EN" => "" ),
	"lastcheckresulttext"=>array("JP"=>"","CN"=>"", "KR"=>"최종점검", "EN" => "" ),
	"allcheckresulttext"=>array("JP"=>"","CN"=>"", "KR"=>"전체점검", "EN" => "" ),
	"checkitemtext"=>array("JP"=>"","CN"=>"", "KR"=>"점검항목", "EN" => "" ),
	"checklisttext"=>array("JP"=>"","CN"=>"", "KR"=>"점검내역", "EN" => "" ),
	"checkdeviceinfotext"=>array("JP"=>"","CN"=>"", "KR"=>"검사 디스크 정보", "EN" => "" ),
	"devicechecklisttext"=>array("JP"=>"","CN"=>"", "KR"=>"장비 점검내역", "EN" => "" ),
	"resolvedresulttext"=>array("JP"=>"0","CN"=>"", "KR"=>"조치결과", "EN" => "" ),
	"weaknessdetectiontext"=>array("JP"=>"0","CN"=>"", "KR"=>"취약점 발견", "EN" => "" ),
	"virusdetectiontext"=>array("JP"=>"0","CN"=>"", "KR"=>"악성코드 발견", "EN" => "" ),
	"unresolvedtext"=>array("JP"=>"0","CN"=>"", "KR"=>"미조치", "EN" => "" ),
	"resolvedtext"=>array("JP"=>"0","CN"=>"", "KR"=>"조치완료", "EN" => "" ),
	"approvedtext"=>array("JP"=>"","CN"=>"", "KR"=>"승인", "EN" => "" ),
	"inspection_center"=>array("JP"=>"","CN"=>"", "KR"=>"검사장", "EN" => "" ),
	"vaccinenametext"=>array("JP"=>"","CN"=>"", "KR"=>"백신명", "EN" => "" ),
	"vaccineupdatedatetext"=>array("JP"=>"","CN"=>"", "KR"=>"백신업데이트일자", "EN" => "" ),
	"scandatetext"=>array("JP"=>"","CN"=>"", "KR"=>"스캔일자", "EN" => "" ),
	"vcsscanresulttext"=>array("JP"=>"","CN"=>"", "KR"=>"VCS 검사 결과", "EN" => "" ),
	"virustext"=>array("JP"=>"","CN"=>"", "KR"=>"악성코드", "EN" => "" ),
	"cleantext"=>array("JP"=>"","CN"=>"", "KR"=>"클린", "EN" => "" ),
	"device"=>array("JP"=>"","CN"=>"", "KR"=>"Device", "EN" => "" ),
	"number_scanned_files"=>array("JP"=>"","CN"=>"", "KR"=>"검사 파일 수", "EN" => "" ),
	"number_imported_files"=>array("JP"=>"","CN"=>"", "KR"=>"반입 파일 수", "EN" => "" ),
	"suspected_forgery"=>array("JP"=>"","CN"=>"", "KR"=>"위변조 의심", "EN" => "" ),
	"malicious_code"=>array("JP"=>"","CN"=>"", "KR"=>"악성코드 발견", "EN" => "" ),
	"virusnametext"=>array("JP"=>"","CN"=>"", "KR"=>"악성코드명", "EN" => "" ),
	"transmethodtext"=>array("JP"=>"","CN"=>"", "KR"=>"처리방법", "EN" => "" ),
	"transsteptext"=>array("JP"=>"","CN"=>"", "KR"=>"처리단계", "EN" => "" ),
	"transresulttext"=>array("JP"=>"","CN"=>"", "KR"=>"처리결과", "EN" => "" ),
	"windowupdateconfirmdatetext"=>array("JP"=>"","CN"=>"", "KR"=>"윈도우즈업데이트 확인일자", "EN" =>"" ), 
	"windowupdateinstalldatetext"=>array("JP"=>"","CN"=>"", "KR"=>"윈도우즈업데이트 설치일자","EN" => "" ), 
	"confirmdatetext"=>array("JP"=>"","CN"=>"", "KR"=>"확인일자", "EN" => "" ),
	"installdatetext"=>array("JP"=>"","CN"=>"", "KR"=>"설치일자", "EN" => "" ),
	"fatchnametext"=>array("JP"=>"","CN"=>"", "KR"=>"패치명", "EN" => "" ),
	"todaystoragecheckstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"오늘 저장매체 점검현황", "EN" => ""), 
	"todaypccheckstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"오늘 노트북 점검현황", "EN" => "" ),
	"checkstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"점검현황", "EN" => "" ),
	"usercheckstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"방문자 점검현황", "EN" => "" ),
	"checkdevicestatustext"=>array("JP"=>"","CN"=>"", "KR"=>"장비별 점검현황", "EN" => "" ),
	"checkdevicelisttext"=>array("JP"=>"","CN"=>"", "KR"=>"장비별 점검내역", "EN" => "" ),
	"thismonthorgancheckstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"이달 기관별 점검현황", "EN" => ""), 
	"thismonthscancentercheckstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"이달 검사장소별 점검현황","EN" => "" ), 
	"organcheckstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"기관별 점검현황", "EN" => ""), 
	"deptcheckstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"부서별 점검현황", "EN" => "" ),
	"weaknessstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"보안 취약현황", "EN" => "" ),
	"typechecktatustext"=>array("JP"=>"","CN"=>"", "KR"=>"매체별 점검현황", "EN" => "" ),
	"virusdectionstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"악성코드 발견현황", "EN" => "" ),
	"usercompanycheckstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"업체별 점검현황", "EN" => "" ),
	"checktext"=>array("JP"=>"","CN"=>"", "KR"=>"점검", "EN" => "" ),
	"checklogtext"=>array("JP"=>"","CN"=>"", "KR"=>"점검이력", "EN" => "" ),
	"pcosstatustext"=>array("JP"=>"","CN"=>"", "KR"=>"운영체제별 노트북 현황", "EN" => "" ),
	"pcmanufacturertext"=>array("JP"=>"","CN"=>"", "KR"=>"제조사별 노트북 현황", "EN" => "" ),
	"logtext"=>array("JP"=>"","CN"=>"", "KR"=>"이력", "EN" => "" ),
	"logviewtext"=>array("JP"=>"","CN"=>"", "KR"=>"이력보기", "EN" => "" ),
	"intext"=>array("JP"=>"","CN"=>"", "KR"=>"반입", "EN" => "" ),
	"nointext"=>array("JP"=>"","CN"=>"", "KR"=>"미반입", "EN" => "" ),
	"send_server"=>array("JP"=>"","CN"=>"", "KR"=>"전송", "EN" => "" ),
	"notsend_server"=>array("JP"=>"","CN"=>"", "KR"=>"미전송", "EN" => "" ),
	"inouttext"=>array("JP"=>"","CN"=>"","KR"=>"반입/반출", "EN" => "" ), 
	"inaccesstext"=>array("JP"=>"","CN"=>"", "KR"=>"반입처리", "EN" => "" ), 
	"outaccesstext"=>array("JP"=>"","CN"=>"", "KR"=>"반출처리", "EN" => "" ),
	"assetoutaccesstext"=>array("JP"=>"","CN"=>"", "KR"=>"자산반출처리", "EN" => "" ),
	"assetoutcancelaccesstext"=>array("JP"=>"","CN"=>"", "KR"=>"자산반출취소", "EN" => "" ),
	"searchtext"=>array("JP"=>"","CN"=>"", "KR"=>"조회", "EN" => "" ),
	"out_access_success"=>array("JP"=>"","CN"=>"", "KR"=>"반출완료", "EN" => "" ),
	"withinonemonthtext"=>array("JP"=>"","CN"=>"", "KR"=>"1개월이내", "EN" => "" ),
	"employeecounttext"=>array("JP"=>"0","CN"=>"", "KR"=>"직원수", "EN" => "ALL" ),
	"employeetext"=>array("JP"=>"0","CN"=>"", "KR"=>"직원", "EN" => "ALL" ),
	"scanprintmessagetext"=>array("JP"=>"0","CN"=>"", "KR"=>"검사 결과지는 반출시까지 보관하시기 바랍니다.", "EN" => "" ), 
	"checkinprocesstext"=>array("JP"=>"0","CN"=>"", "KR"=>"해당 기기를 반입 처리합니다.", "EN" => "" ), 
	"checkoutprocesstext"=>array("JP"=>"0","CN"=>"", "KR"=>"해당 기기를 반출 처리합니다. 반출 취소를 하려면 한번 더 바코드를 스캔해 주세요.", "EN" => "" ),
	"cancelcheckoutprocesstext"=>array("JP"=>"0","CN"=>"", "KR"=>"해당 기기를 반출 취소 처리합니다.","EN" => "" ), 
	"filetypetext"=>array("JP"=>"0","CN"=>"", "KR"=>"파일유형", "EN" => "" ),
	"datalinkservertext"=>array("JP"=>"0","CN"=>"", "KR"=>"데이터 연동서버", "EN" => "" ),
	"datalinkdbiptext"=>array("JP"=>"0","CN"=>"", "KR"=>"데이터 연동DB IP", "EN" => "" ),
	"datalinkurltext"=>array("JP"=>"0","CN"=>"", "KR"=>"데이터 연동 주소 URL", "EN" => "" ),
	"serverconnectchecktypetext"=>array("JP"=>"0","CN"=>"", "KR"=>"서버 연결 확인 방법", "EN" => "" ),
	"devicecontrolusetext"=>array("JP"=>"0","CN"=>"", "KR"=>"매체 제어 사용", "EN" => "" ),
	"deleteyntext"=>array("JP"=>"0","CN"=>"", "KR"=>"삭제여부", "EN" => "Deletion status" ),
	"deletedtext"=>array("JP"=>"0","CN"=>"", "KR"=>"삭제됨", "EN" => "" ),
	"secondtext"=>array("JP"=>"0","CN"=>"", "KR"=>"초", "EN" => "" ),
	"mintext"=>array("JP"=>"0","CN"=>"", "KR"=>"분", "EN" => "" ), 
	"yestext"=>array("JP"=>"0","CN"=>"","KR"=>"예", "EN" => "" ), 
	"notext"=>array("JP"=>"0","CN"=>"", "KR"=>"아니요", "EN" => "" ),
	"linktext"=>array("JP"=>"0","CN"=>"", "KR"=>"연동", "EN" => "" ),
	"wifitext"=>array("JP"=>"0","CN"=>"", "KR"=>"WIFI", "EN" => "" ),
	"bluetoothtext"=>array("JP"=>"0","CN"=>"", "KR"=>"BLUETOOTH", "EN" => "" ),
	"usbtext"=>array("JP"=>"0","CN"=>"", "KR"=>"USB", "EN" => "" ),
	"cdromtext"=>array("JP"=>"0","CN"=>"", "KR"=>"CDROM", "EN" => "" ),
	"serialporttext"=>array("JP"=>"0","CN"=>"", "KR"=>"Serial Port", "EN" => "" ),
	"lantext"=>array("JP"=>"0","CN"=>"", "KR"=>"LAN", "EN" => "" ),
	"webcamtext"=>array("JP"=>"0","CN"=>"", "KR"=>"WEB CAM", "EN" => "" ),
	"wpdtext"=>array("JP"=>"0","CN"=>"", "KR"=>"WPD", "EN" => "" ),
	"sdcardtext"=>array("JP"=>"0","CN"=>"", "KR"=>"SD CARD", "EN" => "" ),
	"volumndrivechecktext"=>array("JP"=>"0","CN"=>"", "KR"=>"볼륨 드라이브 변화체크", "EN" => "" ),
	"volumnunmounttext"=>array("JP"=>"0","CN"=>"", "KR"=>"Volumn Unmount", "EN" => "" ),
	"networksharetext"=>array("JP"=>"0","CN"=>"", "KR"=>"네트워크 공유", "EN" => "" ),
	"viewinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"정보보기", "EN" => "" ),
	"organinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"기관정보", "EN" => "" ),
	"organcodetext"=>array("JP"=>"0","CN"=>"", "KR"=>"기관코드", "EN" => "" ),
	"organnametext"=>array("JP"=>"0","CN"=>"", "KR"=>"기관명", "EN" => "" ), 
	"centercodetext"=>array("JP"=>"Center code", "CN"=>"中心代码", "KR"=>"검사장코드", "EN" => "Center code" ), 
	"centernametext"=>array("JP"=>"Center name", "CN"=>"中心名", "KR"=>"검사장명", "EN" => "Center name" ), 
	"codetext"=>array("JP"=>"0","CN"=>"", "KR"=>"코드", "EN" => "" ),
	"codenametext"=>array("JP"=>"0","CN"=>"", "KR"=>"코드명", "EN" => "" ),
	"codevaluetext"=>array("JP"=>"0","CN"=>"", "KR"=>"코드값", "EN" => "" ),
	"unchangeabletext"=>array("JP"=>"0","CN"=>"", "KR"=>"수정불가능", "EN" => "" ),
	"addcodeclassificationtext"=>array("JP"=>"0","CN"=>"", "KR"=>"코드분류추가", "EN" => "" ),
	"addcodedetailclassificationtext"=>array("JP"=>"0","CN"=>"", "KR"=>"코드분류상세추가", "EN" => "" ),
	"codeclassificationnametext"=>array("JP"=>"0","CN"=>"", "KR"=>"코드분류명", "EN" => "" ),
	"codeclassificationvaluetext"=>array("JP"=>"0","CN"=>"", "KR"=>"코드분류값", "EN" => "" ),
	"codeclassificationvaluecreateguidetext"=>array("JP"=>"0","CN"=>"", "KR"=>"※ 영문 대문자,숫자,특수문자 하이픈(-) 조합으로 입력", "EN" => "" ),
	"groupnametext"=>array("JP"=>"0","CN"=>"", "KR"=>"그룹명", "EN" => "" ),
	"groupdescriptiontext"=>array("JP"=>"0","CN"=>"", "KR"=>"그룹설명", "EN" => "" ),
	"companyinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"회사 정보", "EN" => "" ),
	"systeminfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"시스템 정보", "EN" => "" ),
	"systemversionchangetext"=>array("JP"=>"0","CN"=>"", "KR"=>"시스템버전 변경", "EN" => "" ),
	"systemversionidtext"=>array("JP"=>"0","CN"=>"", "KR"=>"시스템 버전", "EN" => "" ),
	"systemversionnametext"=>array("JP"=>"0","CN"=>"", "KR"=>"시스템 버전명", "EN" => "" ),
	"systemgubuntext"=>array("JP"=>"0","CN"=>"", "KR"=>"시스템 구분", "EN" => "" ),
	"licensetypetext"=>array("JP"=>"0","CN"=>"", "KR"=>"라이센스 구분", "EN" => "" ),
	"systemdesctext"=>array("JP"=>"0","CN"=>"", "KR"=>"시스템 설명", "EN" => "" ),
	"organtext"=>array("JP"=>"0","CN"=>"", "KR"=>"기관", "EN" => "" ),
	"manageorgantext"=>array("JP"=>"0","CN"=>"", "KR"=>"관리기관", "EN" => "" ),
	"managescancentertext"=>array("JP"=>"0","CN"=>"", "KR"=>"관리검사장", "EN" => "" ),
	"scancentertext"=>array("JP"=>"0","CN"=>"", "KR"=>"검사장", "EN" => "" ),
	"scancenterchoosetext"=>array("JP"=>"0","CN"=>"", "KR"=>"검사장선택", "EN" => "" ),
	"belongorgantext"=>array("JP"=>"0","CN"=>"", "KR"=>"소속기관", "EN" => "" ),
	"superdepttext"=>array("JP"=>"0","CN"=>"", "KR"=>"상위부서", "EN" => "" ),
	"useyntext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용여부", "EN" => "" ),
	"pcuseyntext"=>array("JP"=>"0","CN"=>"", "KR"=>"노트북 사용여부", "EN" => "" ),
	"sorttext"=>array("JP"=>"0","CN"=>"", "KR"=>"정렬", "EN" => "" ),
	"sortordertext"=>array("JP"=>"0","CN"=>"", "KR"=>"정렬순서", "EN" => "" ),
	"deptauthtext"=>array("JP"=>"0","CN"=>"", "KR"=>"부서권한", "EN" => "" ),
	"deletetext"=>array("JP"=>"0","CN"=>"", "KR"=>"삭제", "EN" => "" ),
	"reasontext"=>array("JP"=>"0","CN"=>"", "KR"=>"사유", "EN" => "" ),
	"periodtext"=>array("JP"=>"0","CN"=>"", "KR"=>"기간", "EN" => "" ),
	"dayperiodtext"=>array("JP"=>"0","CN"=>"", "KR"=>"기간(일)", "EN" => "" ),
	"issuertext"=>array("JP"=>"0","CN"=>"", "KR"=>"발급자", "EN" => "" ),
	"issuedatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"발급일", "EN" => "" ),
	"versioninfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"버전정보", "EN" => "" ),
	"updatetimeinputguidetext"=>array("JP"=>"0","CN"=>"", "KR"=>"*입력형식: 2018-01-01 15:30:15", "EN" => "" ), 
	"installpathtext"=>array("JP"=>"0","CN"=>"", "KR"=>"설치경로", "EN" => "" ),
	"installyestext"=>array("JP"=>"0","CN"=>"", "KR"=>"설치", "EN" => "" ),
	"installnotext"=>array("JP"=>"0","CN"=>"", "KR"=>"설치안함", "EN" => "" ),
	"insideiprangetext"=>array("JP"=>"0","CN"=>"", "KR"=>"사내 IP 범위", "EN" => "" ),
	"userangetext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용 범위", "EN" => "" ),
	"iptext"=>array("JP"=>"0","CN"=>"IP", "KR"=>"IP", "EN" => "IP" ),
	"appnfilenametext"=>array("JP"=>"0","CN"=>"", "KR"=>"APP/파일명", "EN" => "" ),
	"downloadlinktext"=>array("JP"=>"0","CN"=>"", "KR"=>"다운로드링크", "EN" => "" ),
	"appnametext"=>array("JP"=>"0","CN"=>"", "KR"=>"APP명", "EN" => "" ),
	"filenametext"=>array("JP"=>"0","CN"=>"", "KR"=>"파일명", "EN" => "" ),
	"confirmed_person"=>array("JP"=>"0","CN"=>"", "KR"=>"확장자", "EN" => "confirmed person" ),
	"filepathtext"=>array("JP"=>"0","CN"=>"", "KR"=>"파일경로", "EN" => "File path" ),
	"filesizetext"=>array("JP"=>"0","CN"=>"", "KR"=>"파일크기", "EN" => "file size" ),
	"updatetimetext"=>array("JP"=>"0","CN"=>"", "KR"=>"업데이트 기준시간", "EN" => "" ),
	"nametext"=>array("JP"=>"0","CN"=>"", "KR"=>"이름", "EN" => "Name" ),
	"descriptiontext"=>array("JP"=>"0","CN"=>"", "KR"=>"설명", "EN" => "" ),
	"adminloginlogtext"=>array("JP"=>"0","CN"=>"", "KR"=>"관리자접속내역", "EN" => "" ),
	"counttext"=>array("JP"=>"0","CN"=>"", "KR"=>"건", "EN" => "" ),
	"usersearchinputguidetext"=>array("JP"=>"0","CN"=>"", "KR"=>"사원명 또는 사번을 입력하세요.", "EN" => "" ), 
	"ipaddresstext"=>array("JP"=>"0","CN"=>"", "KR"=>"IP 주소", "EN" => "" ),
	"inputipaddresstext"=>array("JP"=>"0","CN"=>"", "KR"=>"IP 주소를 입력하세요", "EN" => "" ),
	"loginusertext"=>array("JP"=>"0","CN"=>"", "KR"=>"로그인 사용자", "EN" => "" ),
	"datetext"=>array("JP"=>"0","CN"=>"", "KR"=>"일자", "EN" => "" ),
	"logindatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"접속일자", "EN" => "" ),
	"recentlogindatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"최근접속일자", "EN" => "" ),
	"logincounttext"=>array("JP"=>"0","CN"=>"", "KR"=>"로그인횟수", "EN" => "" ),
	"logindetailinfo"=>array("JP"=>"0","CN"=>"", "KR"=>"로그인상세정보", "EN" => "" ),
	"initialpasswordguidetext"=>array("JP"=>"0","CN"=>"", "KR"=>"비밀번호를 다시 입력하지 않으면 초기비밀번호는 **** 로 등록됩니다", "EN" => "" ),
	"passwordchangerequesttext1"=>array("JP"=>"0","CN"=>"", "KR"=>"최초 로그인시 비밀번호 변경이 필요합니다.", "EN" => "" ), 
	"passwordchangerequesttext2"=>array("JP"=>"0","CN"=>"", "KR"=>"비밀번호 변경주기가 경과하였습니다. 비밀번호 변경이 필요합니다.", "EN" => "" ),
	"passwordchangerequesttext3"=>array("JP"=>"0","CN"=>"", "KR"=>"관리자에 의해 비밀번호가 변경되었습니다. 비밀번호 변경이 필요합니다.", "EN" => "" ),
	"nohavepctext"=>array("JP"=>"0","CN"=>"", "KR"=>"보유 노트북이 없습니다.", "EN" => "" ),
	"onedaywindowhidetext"=>array("JP"=>"0","CN"=>"", "KR"=>"오늘 하루동안 보이지 않음.", "EN" => "" ),
	"daytext"=>array("JP"=>"0","CN"=>"", "KR"=>"일", "EN" => "" ),
	"monthtext"=>array("JP"=>"0","CN"=>"", "KR"=>"월", "EN" => "" ),
	"weektext"=>array("JP"=>"0","CN"=>"", "KR"=>"요일", "EN" => "" ),
	"yeartext"=>array("JP"=>"0","CN"=>"", "KR"=>"년", "EN" => "" ),
	"hourtext"=>array("JP"=>"0","CN"=>"", "KR"=>"시간", "EN" => "" ),
	"hourtimetext"=>array("JP"=>"0","CN"=>"", "KR"=>"시", "EN" => "" ),
	"chooseyeartext"=>array("JP"=>"0","CN"=>"", "KR"=>"년도선택", "EN" => "" ),
	"choosetexts"=>array("JP"=>"0","CN"=>"", "KR"=>"선택", "EN" => "" ),
	"choosemonthtext"=>array("JP"=>"0","CN"=>"", "KR"=>"월선택", "EN" => "" ),
	"useyestext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용", "EN" => "" ),
	"usenotext"=>array("JP"=>"0","CN"=>"", "KR"=>"사용안함", "EN" => "" ),
	"adminauthtext"=>array("JP"=>"0","CN"=>"", "KR"=>"관리자권한", "EN" => "" ),
	"menuauthtext"=>array("JP"=>"0","CN"=>"", "KR"=>"메뉴권한", "EN" => "" ),
	"organauthtext"=>array("JP"=>"0","CN"=>"", "KR"=>"기관권한", "EN" => "" ),
	"scancenterauthtext"=>array("JP"=>"0","CN"=>"", "KR"=>"검사장권한", "EN" => "" ),
	"basicinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"기본정보", "EN" => "" ),
	"detailinfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"상세정보", "EN" => "" ),
	"admininfotext"=>array("JP"=>"0","CN"=>"", "KR"=>"관리자정보", "EN" => "" ),
	"emppolicytext"=>array("JP"=>"0","CN"=>"", "KR"=>"개인운영정책", "EN" => "" ),
	"fileDownloadText"=>array("JP"=>"0","CN"=>"", "KR"=>"파일다운로드", "EN" => "" ),
	"filenotfoundtext"=>array("JP"=>"0","CN"=>"文件不存在。", "KR"=>"파일이 존재하지 않습니다.", "EN" => "No file found." ), 
	"choosetext"=>array("JP"=>"0","CN"=>"", "KR"=>"선택하세요.", "EN" => "" ),
	"duplicatecodetext"=>array("JP"=>"0","CN"=>"", "KR"=>"중복된 코드입니다.", "EN" => "" ),
	"reportprintsettext"=>array("JP"=>"0","CN"=>"", "KR"=>"리포트출력설정", "EN" => "" ),
	"reportertext"=>array("JP"=>"0","CN"=>"", "KR"=>"보고자", "EN" => "" ),
	"reportdatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"보고일시", "EN" => "" ),
	"printperiodtext"=>array("JP"=>"0","CN"=>"", "KR"=>"출력기간", "EN" => "" ),
	"statisticstext"=>array("JP"=>"0","CN"=>"", "KR"=>"통계", "EN" => "" ),
	"printoptiontext"=>array("JP"=>"0","CN"=>"", "KR"=>"출력옵션", "EN" => "" ),
	"dailytext"=>array("JP"=>"0","CN"=>"", "KR"=>"일별", "EN" => "" ),
	"monthlytext"=>array("JP"=>"0","CN"=>"", "KR"=>"월별", "EN" => "" ),
	"byperiodtext"=>array("JP"=>"0","CN"=>"", "KR"=>"기간별", "EN" => "" ),
	"reporttitletext"=>array("JP"=>"0","CN"=>"", "KR"=>"{yyyy}년 VCS 보고서", "EN" => "" ),
	"reportcoverprinttext"=>array("JP"=>"0","CN"=>"", "KR"=>"표지포함 인쇄", "EN" => "" ),
	"dailyvcsstatustext"=>array("JP"=>"0","CN"=>"", "KR"=>"일별 점검현황", "EN" => "" ),
	"monthlyvcsstatustext"=>array("JP"=>"0","CN"=>"", "KR"=>"월별 점검현황", "EN" => "" ),
	"dailydevicevcsstatustext"=>array("JP"=>"0","CN"=>"", "KR"=>"일별 장비 점검현황", "EN" => "" ),
	"monthlydevicevcsstatustext"=>array("JP"=>"0","CN"=>"", "KR"=>"월별 장비 점검현황", "EN" => "" ),
	"weaknessnvirusstatustext"=>array("JP"=>"0","CN"=>"", "KR"=>"취약점/악성코드 현황", "EN" => "" ),
	"companyvcsstatustext"=>array("JP"=>"0","CN"=>"", "KR"=>"업체별 점검현황", "EN" => "" ),
	"weaknesslisttext"=>array("JP"=>"0","CN"=>"", "KR"=>"취약점 내역", "EN" => "" ),
	"viruslisttext"=>array("JP"=>"0","CN"=>"", "KR"=>"악성코드 내역", "EN" => "" ),
	"detectcounttext"=>array("JP"=>"0","CN"=>"", "KR"=>"탐지건수", "EN" => "" ),
	"btngobeforepage"=>array("JP"=>"0","CN"=>"", "KR"=>"< 이전 페이지 가기", "EN" => "" ),
	"btnlogin"=>array("JP"=>"0","CN"=>"", "KR"=>"로그인", "EN" => "" ),
	"btnchangepassword"=>array("JP"=>"0","CN"=>"", "KR"=>"비밀번호 변경", "EN" => "" ),
	"btnmore"=>array("JP"=>"0","CN"=>"", "KR"=>"더보기", "EN" => "" ),
	"btnview"=>array("JP"=>"0","CN"=>"", "KR"=>"보기", "EN" => "" ),
	"btnregist"=>array("JP"=>"0","CN"=>"", "KR"=>"등록", "EN" => "" ),
	"btnlist"=>array("JP"=>"0","CN"=>"", "KR"=>"목록", "EN" => "" ),
	"btnlisttext"=>array("JP"=>"0","CN"=>"", "KR"=>"목록으로", "EN" => "" ),
	"btnupdate"=>array("JP"=>"0","CN"=>"", "KR"=>"수정", "EN" => "" ),
	"btnsave"=>array("JP"=>"0","CN"=>"", "KR"=>"저장", "EN" => "" ),
	"btnsavetext"=>array("JP"=>"0","CN"=>"", "KR"=>"저장하기", "EN" => "" ),
	"btnregisttext"=>array("JP"=>"Regist", "CN"=>"등록하기", "KR"=>"등록하기", "EN" => "Regist" ),
	"btndelete"=>array("JP"=>"0","CN"=>"", "KR"=>"삭제", "EN" => "" ),
	"btndeletetext"=>array("JP"=>"0","CN"=>"", "KR"=>"삭제하기", "EN" => "" ),
	"btnclear"=>array("JP"=>"0","CN"=>"", "KR"=>"초기화", "EN" => "" ),
	"btnnext"=>array("JP"=>"0","CN"=>"", "KR"=>"다음", "EN" => "" ),
	"btnprev"=>array("JP"=>"0","CN"=>"", "KR"=>"이전", "EN" => "" ),
	"btnorganregist"=>array("JP"=>"0","CN"=>"", "KR"=>"기관등록", "EN" => "" ),
	"btndeptregist"=>array("JP"=>"0","CN"=>"", "KR"=>"부서추가", "EN" => "" ),
	"btnuserregist"=>array("JP"=>"0","CN"=>"", "KR"=>"사용자추가", "EN" => "" ),
	"btnempregist"=>array("JP"=>"0","CN"=>"", "KR"=>"임직원추가", "EN" => "" ),
	"btnfind"=>array("JP"=>"0","CN"=>"", "KR"=>"검색", "EN" => "" ),
	"btncurrenttime"=>array("JP"=>"0","CN"=>"", "KR"=>"현재시간", "EN" => "" ),
	"btnapply"=>array("JP"=>"0","CN"=>"", "KR"=>"신청", "EN" => "" ),
	"btnconfirm"=>array("JP"=>"0","CN"=>"", "KR"=>"확인", "EN" => "" ),
	"btnexceldownload"=>array("JP"=>"0","CN"=>"", "KR"=>"엑셀 파일로 저장하기", "EN" => "" ),
	"save_file"=>array("JP"=>"0","CN"=>"", "KR"=>"저장하기", "EN" => "" ),
	"import_type"=>array("JP"=>"0","CN"=>"", "KR"=>"반입유형", "EN" => "" ),
	"product_name"=>array("JP"=>"0","CN"=>"", "KR"=>"물품명", "EN" => "" ),
	"serial_number"=>array("JP"=>"0","CN"=>"", "KR"=>"Serial Number", "EN" => "" ),
	"count"=>array("JP"=>"0","CN"=>"", "KR"=>"수량", "EN" => "" ),
	"scheduled_text"=>array("JP"=>"0","CN"=>"", "KR"=>"반출예정", "EN" => "" ),
	"model"=>array("JP"=>"0","CN"=>"", "KR"=>"Model", "EN" => "" ),
	"btnsearch"=>array("JP"=>"0","CN"=>"", "KR"=>"검색", "EN" => "" ),
	"btnadd"=>array("JP"=>"0","CN"=>"", "KR"=>"추가", "EN" => "" ), 
	"btnin"=>array("JP"=>"0","CN"=>"","KR"=>"반입", "EN" => "" ), 
	"btnout"=>array("JP"=>"0","CN"=>"", "KR"=>"반출", "EN" => "" ),
	"btnincancel"=>array("JP"=>"0","CN"=>"", "KR"=>"반입취소", "EN" => "" ),
	"btnoutcancel"=>array("JP"=>"0","CN"=>"", "KR"=>"반출취소", "EN" => "" ),
	"btninout"=>array("JP"=>"0","CN"=>"", "KR"=>"반입/출입", "EN" => "" ),
	"btncancel"=>array("JP"=>"0","CN"=>"", "KR"=>"취소", "EN" => "" ),
	"btnsetcheckitem"=>array("JP"=>"0","CN"=>"", "KR"=>"검사항목 설정", "EN" => "" ),
	"btnresend"=>array("JP"=>"0","CN"=>"", "KR"=>"재전송", "EN" => "" ),
	"btncenterregist"=>array("JP"=>"0","CN"=>"", "KR"=>"검사장등록", "EN" => "" ),
	"btnuserinfoedit"=>array("JP"=>"0","CN"=>"", "KR"=>"사용자 정보 수정", "EN" => "" ),
	"btnvisitorinfoedit"=>array("JP"=>"0","CN"=>"", "KR"=>"방문자 정보 수정", "EN" => "" ),
	"btncompanyinfoedit"=>array("JP"=>"0","CN"=>"", "KR"=>"회사 정보 수정", "EN" => "" ),
	"btncheckinscanlog"=>array("JP"=>"0","CN"=>"", "KR"=>"바코드스캔로그보기", "EN" => "" ),
	"btnchangemodecheckinout"=>array("JP"=>"0","CN"=>"", "KR"=>"반출입모드로 전환", "EN" => "" ),
	"btnscanresultprint"=>array("JP"=>"0","CN"=>"", "KR"=>"검사확인증인쇄", "EN" => "" ),
	"btnprint"=>array("JP"=>"0","CN"=>"", "KR"=>"인쇄하기", "EN" => "" ),
	"btnprint2"=>array("JP"=>"0","CN"=>"", "KR"=>"인쇄", "EN" => "" ),
	"btnpreview"=>array("JP"=>"0","CN"=>"", "KR"=>"미리보기", "EN" => "" ),
	"scanfilecount"=>array("JP"=>"0","CN"=>"", "KR"=>"검사파일수", "EN" => "" ),
	"importfilecount"=>array("JP"=>"0","CN"=>"", "KR"=>"반입파일수", "EN" => "" ),
	"sendfilecount"=>array("JP"=>"0","CN"=>"", "KR"=>"전송파일수", "EN" => "" ),
	"btnchangemodesearch"=>array("JP"=>"0","CN"=>"", "KR"=>"조회모드로 전환", "EN" => "" ),
	"datakeepdaytext"=>array("JP"=>"0","CN"=>"", "KR"=>"데이터 보관 기간", "EN" => "" ),
	"weaknesscleantext"=>array("JP"=>"0","CN"=>"", "KR"=>"취약점조치", "EN" => "" ),
	"viruscleantext"=>array("JP"=>"0","CN"=>"", "KR"=>"악성코드발견", "EN" => "" ),
	"storagemediaintypetext"=>array("JP"=>"0","CN"=>"", "KR"=>"저장매체 반입형태", "EN" => "" ),
	"storagemediafilesendtypetext"=>array("JP"=>"0","CN"=>"", "KR"=>"저장매체 반입파일 전송", "EN" => ""), 
	"storagemediafileserversendtype"=>array("JP"=>"0","CN"=>"", "KR"=>"반입파일 서버 보관", "EN" => ""), 
	"storagemediaintext"=>array("JP"=>"0","CN"=>"", "KR"=>"매체 반입", "EN" => "" ),
	"onlyfileintext"=>array("JP"=>"0","CN"=>"", "KR"=>"파일만 반입", "EN" => "" ),
	"nosendtext"=>array("JP"=>"0","CN"=>"", "KR"=>"전송안함", "EN" => "" ),
	"free_wifi"=>array("JP"=>"0","CN"=>"", "KR"=>"무료 Wi-fi", "EN" => "" ),
	"filesendtext"=>array("JP"=>"0","CN"=>"", "KR"=>"파일전송", "EN" => "" ),
	"onlyfilelistsendtext"=>array("JP"=>"0","CN"=>"", "KR"=>"파일목록만 전송", "EN" => "" ),
	"importfilehistory"=>array("JP"=>"0","CN"=>"", "KR"=>"파일반입내역", "EN" => "" ),
	"sendfilehistory"=>array("JP"=>"0","CN"=>"", "KR"=>"파일전송내역", "EN" => "" ),
	"importfiletext"=>array("JP"=>"0","CN"=>"", "KR"=>"반입파일", "EN" => "" ),
	"sendstatustext"=>array("JP"=>"0","CN"=>"", "KR"=>"전송상태", "EN" => "" ),
	"senddatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"전송일자", "EN" => "" ),
	"senddatetext"=>array("JP"=>"0","CN"=>"", "KR"=>"전송일자", "EN" => "" ),
	"notallowiptext"=>array("JP"=>"Connection is not possible from this IP.", "CN"=>"无法从该 IP 连接.", "KR"=>"해당 IP에서는 접속이 불가능합니다.", "EN" => "Connection is not possible from this IP." ),
	"importdatetimetext"=>array("JP"=>"0","CN"=>"", "KR"=>"반입일시", "EN" => "" )
	,"filescanadapttext"=>array("JP"=>"0","CN"=>"", "KR"=>"파일검사 적용", "EN" => "" ) 
	,"suspectforgerytext"=>array("JP"=>"0","CN"=>"", "KR"=>"위변조 의심", "EN" => "" ) 
	,"rentingitems"=>array("JP"=>"0","CN"=>"", "KR"=>"물품대여항목", "EN" => "" ) 
	,"scanfiletext"=>array("JP"=>"0","CN"=>"", "KR"=>"검사파일", "EN" => "" ) 
	,"purpose_visit"=>array("JP"=>"0","CN"=>"", "KR"=>"방문목적", "EN" => "" ) 
	,"electronic_payment_document_number"=>array("JP"=>"0","CN"=>"", "KR"=>"전자문서번호", "EN" => "" ) 
	,"detailstext"=>array("JP"=>"0","CN"=>"", "KR"=>"상세", "EN" => "" ) 
	,"status_bringingin"=>array("JP"=>"0","CN"=>"", "KR"=>"외부 전산기기 반출입 현황", "EN" => "" ) 
	,"belongtext"=>array("JP"=>"0","CN"=>"", "KR"=>"소속", "EN" => "" )
	,"emailtext"=>array("JP"=>"0","CN"=>"", "KR"=>"이메일", "EN" => "" )
	,"dateFirstVisit"=>array("JP"=>"0","CN"=>"", "KR"=>"최초 방문일", "EN" => "" )
	,"finalVisit"=>array("JP"=>"0","CN"=>"", "KR"=>"최종 방문일", "EN" => "" )
	,"totalNumberVisit"=>array("JP"=>"0","CN"=>"", "KR"=>"출입 횟수", "EN" => "" )
	,"numberImports"=>array("JP"=>"0","CN"=>"", "KR"=>"반입 횟수", "EN" => "" )
	,"btnwrite"=>array("JP"=>"0","CN"=>"", "KR"=>"쓰기", "EN" => "" )
	,"entryExitHistory"=>array("JP"=>"0","CN"=>"", "KR"=>"출입내역", "EN" => "" )
	,"personInCharge"=>array("JP"=>"0","CN"=>"", "KR"=>"담당 출입 현황", "EN" => "" )
	,"departmentText"=>array("JP"=>"0","CN"=>"", "KR"=>"소속 부서", "EN" => "" )
	,"totalNumberImport"=>array("JP"=>"0","CN"=>"", "KR"=>"총 반입 횟수", "EN" => "" )
	,"statisticsVisitor"=>array("JP"=>"0","CN"=>"", "KR"=>"출입자별 통계", "EN" => "" )
	,"rentalDate"=>array("JP"=>"0","CN"=>"", "KR"=>"대여 일자", "EN" => "" )
	,"select_rental_item"=>array("JP"=>"0","CN"=>"", "KR"=>"대여항목선택", "EN" => "" )
	,"unrecovered_views"=>array("JP"=>"0","CN"=>"", "KR"=>"미회수 조회", "EN" => "" )
	,"rentalItems"=>array("JP"=>"0","CN"=>"", "KR"=>"대여물품", "EN" => "" )
	,"itemnumber"=>array("JP"=>"0","CN"=>"", "KR"=>"물품번호", "EN" => "" )
	,"rentaldate"=>array("JP"=>"0","CN"=>"", "KR"=>"대여일자", "EN" => "" )
	,"returndate"=>array("JP"=>"0","CN"=>"", "KR"=>"반납일자", "EN" => "" )
	,"recoveryprocessing"=>array("JP"=>"0","CN"=>"", "KR"=>"회수처리", "EN" => "" )
	,"detailed_product_rental_information"=>array("JP"=>"0","CN"=>"", "KR"=>"물품 대여정보 상세", "EN" => "" )
	,"affiliation_classification"=>array("JP"=>"0","CN"=>"", "KR"=>"소속구분", "EN" => "" )
	,"affiliation_or_team_name"=>array("JP"=>"0","CN"=>"", "KR"=>"소속 또는 팀명", "EN" => "" )
	,"rentalitems"=>array("JP"=>"0","CN"=>"", "KR"=>"대여 물품", "EN" => "" )
	,"rental_device_item_number"=>array("JP"=>"0","CN"=>"", "KR"=>"대여기기 물품번호", "EN" => "" )
	,"rental_location"=>array("JP"=>"0","CN"=>"", "KR"=>"대여장소", "EN" => "" )
	,"rental_purpose"=>array("JP"=>"0","CN"=>"", "KR"=>"대여용도", "EN" => "" )
	,"collection_date"=>array("JP"=>"0","CN"=>"", "KR"=>"회수일자", "EN" => "" )
	,"parking_ticket_payment_details"=>array("JP"=>"0","CN"=>"", "KR"=>"주차권 지급내역", "EN" => "" )
	,"payment_date"=>array("JP"=>"0","CN"=>"", "KR"=>"지급 일자", "EN" => "" )
	,"carnumber"=>array("JP"=>"0","CN"=>"", "KR"=>"차량번호", "EN" => "" )
	,"requesttime"=>array("JP"=>"0","CN"=>"", "KR"=>"요청시간", "EN" => "" )
	,"payment_date"=>array("JP"=>"0","CN"=>"", "KR"=>"지급 일자", "EN" => "" )
	,"parking_ticket_payment_details_theme"=>array("JP"=>"0","CN"=>"", "KR"=>"주차권 지급 상세", "EN" => "" )
	,"paymentdate"=>array("JP"=>"0","CN"=>"", "KR"=>"지급일자", "EN" => "" )
	,"trainingdate"=>array("JP"=>"0","CN"=>"", "KR"=>"교육일자", "EN" => "" )
	,"projectname"=>array("JP"=>"0","CN"=>"", "KR"=>"프로젝트명", "EN" => "" )
	,"compname"=>array("JP"=>"0","CN"=>"", "KR"=>"업체명", "EN" => "" )
	,"inputname"=>array("JP"=>"0","CN"=>"", "KR"=>"투입인력이름", "EN" => "" )
	,"trainingmanager"=>array("JP"=>"0","CN"=>"", "KR"=>"교육담당자이름", "EN" => "" )
	,"trainingstaff"=>array("JP"=>"0","CN"=>"", "KR"=>"교육담당자소속", "EN" => "" )
	,"companyname_text"=>array("JP"=>"0","CN"=>"", "KR"=>"업체명", "EN" => "" )
	,"user_name_kr"=>array("JP"=>"0","CN"=>"", "KR"=>"투입인력 이름", "EN" => "" )
	,"user_en_id"=>array("JP"=>"0","CN"=>"", "KR"=>"교육생 영문명", "EN" => "" )
	,"manager_en_id"=>array("JP"=>"0","CN"=>"", "KR"=>"담당자 영문명", "EN" => "" )
	,"manpower_input"=>array("JP"=>"0","CN"=>"", "KR"=>"투입인력", "EN" => "" )
	,"engnameid"=>array("JP"=>"0","CN"=>"", "KR"=>"영문 이름", "EN" => "" )
	,"training_date"=>array("JP"=>"0","CN"=>"", "KR"=>"교육일자", "EN" => "" )
	,"manager_name_kr"=>array("JP"=>"0","CN"=>"", "KR"=>"교육 담당자 이름", "EN" => "" )
	,"education_manager_affiliation"=>array("JP"=>"0","CN"=>"", "KR"=>"교육담당자 소속", "EN" => "" )
	,"education_manager"=>array("JP"=>"0","CN"=>"", "KR"=>"교육담당자", "EN" => "" )
	,"education_manager_eng_id"=>array("JP"=>"0","CN"=>"", "KR"=>"교육담당자 영문명", "EN" => "" )
	,"department_of_education"=>array("JP"=>"0","CN"=>"", "KR"=>"교육 담당자 소속", "EN" => "" )
	,"inspection_date"=>array("JP"=>"0","CN"=>"", "KR"=>"점검 일자", "EN" => "" )
	,"inspection_equipment"=>array("JP"=>"0","CN"=>"", "KR"=>"검사 장비", "EN" => "" )
	,"progresstext"=>array("JP"=>"0","CN"=>"", "KR"=>"진행 상태", "EN" => "" )
	,"check_results"=>array("JP"=>"0","CN"=>"", "KR"=>"점검 결과", "EN" => "" )
	,"select_progress_status"=>array("JP"=>"0","CN"=>"", "KR"=>"진행상태선택", "EN" => "" )
	,"serialnumber"=>array("JP"=>"0","CN"=>"", "KR"=>"시리얼번호", "EN" => "" )
	,"inspection_datetext"=>array("JP"=>"0","CN"=>"", "KR"=>"점검일자", "EN" => "" )
	,"number_inspection_files"=>array("JP"=>"0","CN"=>"", "KR"=>"검사파일수", "EN" => "" )
	,"number_import_files"=>array("JP"=>"0","CN"=>"", "KR"=>"반입 파일수", "EN" => "" )
	,"result_list_details"=>array("JP"=>"0","CN"=>"", "KR"=>"점검결과 상세", "EN" => "" )
	,"inspection_site_date"=>array("JP"=>"0","CN"=>"", "KR"=>"검사장/점검일", "EN" => "" )
	,"visitor_affiliation"=>array("JP"=>"0","CN"=>"", "KR"=>"방문객/소속", "EN" => "" )
	,"inoutstatus"=>array("JP"=>"0","CN"=>"", "KR"=>"출입현황", "EN" => "" )
	,"dailyinoutstatus"=>array("JP"=>"0","CN"=>"", "KR"=>"일별 출입현황", "EN" => "" )
	,"monthlyinoutstatus"=>array("JP"=>"0","CN"=>"", "KR"=>"월별 출입현황", "EN" => "" )
	,"inspection_equipment"=>array("JP"=>"0","CN"=>"", "KR"=>"점검장비", "EN" => "" )
	,"contact_person_or_department"=>array("JP"=>"0","CN"=>"", "KR"=>"담당자/부서", "EN" => "" )
	,"inspec_info"=>array("JP"=>"0","CN"=>"", "KR"=>"검사 정보", "EN" => "" )
	,"item_rental_status"=>array("JP"=>"0","CN"=>"", "KR"=>"물품대여현황", "EN" => "" )
	,"itemrentstatus"=>array("JP"=>"0","CN"=>"", "KR"=>"품목임대상태", "EN" => "" )
	,"searchperiod"=>array("JP"=>"0","CN"=>"", "KR"=>"검사 기간", "EN" => "" )
	,"connection_ip"=>array("JP"=>"0","CN"=>"", "KR"=>"접속 IP", "EN" => "" )
	,"chart_data_table"=>array("JP"=>"0","CN"=>"", "KR"=>"차트 데이터 표", "EN" => "" )
	,"view_data_table"=>array("JP"=>"0","CN"=>"", "KR"=>"데이터 표 보기", "EN" => "" )
	,"totaltext"=>array("JP"=>"0","CN"=>"", "KR"=>"계", "EN" => "" )
	,"umbrella"=>array("JP"=>"0","CN"=>"", "KR"=>"우산", "EN" => "" )
	,"pointer"=>array("JP"=>"0","CN"=>"", "KR"=>"포인터", "EN" => "" )
	,"institution_settings"=>array("JP"=>"0","CN"=>"", "KR"=>"기관설정", "EN" => "" )
	,"inspection_site_settings"=>array("JP"=>"0","CN"=>"", "KR"=>"검사장설정", "EN" => "" )
	,"empname"=>array("JP"=>"0","CN"=>"", "KR"=>"이름", "EN" => "" )
	,"deptname"=>array("JP"=>"0","CN"=>"", "KR"=>"소속", "EN" => "" )
	,"carnumber"=>array("JP"=>"0","CN"=>"", "KR"=>"차량번호", "EN" => "" )
	,"return_schedule_date_text"=>array("JP"=>"0","CN"=>"", "KR"=>"반납예정일", "EN" => "" )
	,"out_worker_text"=>array("JP"=>"0","CN"=>"", "KR"=>"외부직원", "EN" => "" )
	,"recovery_text"=>array("JP"=>"0","CN"=>"", "KR"=>"회수", "EN" => "" )
	,"retriver_text"=>array("JP"=>"0","CN"=>"", "KR"=>"회수자", "EN" => "" )
	,"recovery_success_text"=>array("JP"=>"0","CN"=>"", "KR"=>"회수완료", "EN" => "" )
	,"dept_or_team_text"=>array("JP"=>"0","CN"=>"", "KR"=>"소속또는팀", "EN" => "" )
	,"unrecover_text"=>array("JP"=>"0","CN"=>"", "KR"=>"회수취소", "EN" => "" )
	,"out_manager_text"=>array("JP"=>"0","CN"=>"", "KR"=>"외주관리자", "EN" => "" )
	,"onsite_agent_text"=>array("JP"=>"0","CN"=>"", "KR"=>"현장대리인", "EN" => "" )
	,"classify_edu"=>array("JP"=>"0","CN"=>"", "KR"=>"교육담당자 구분", "EN" => "" )
	,"application_entry_text"=>array("JP"=>"0","CN"=>"", "KR"=>"출입신청", "EN" => "" )
	,"tempoprary_pass_text"=>array("JP"=>"0","CN"=>"", "KR"=>"임시출입증발급", "EN" => "" )
	,"tempoprary_pass_info_text"=>array("JP"=>"0","CN"=>"", "KR"=>"임시출입증 발급정보", "EN" => "" )
	,"tempoprary_pass_no"=>array("JP"=>"0","CN"=>"", "KR"=>"임시출입증번호", "EN" => "" )
	,"return_process"=>array("JP"=>"0","CN"=>"", "KR"=>"반납처리", "EN" => "" )
	,"returner_person"=>array("JP"=>"0","CN"=>"", "KR"=>"반납처리자", "EN" => "" )
	,"return_success"=>array("JP"=>"0","CN"=>"", "KR"=>"반납완료", "EN" => "" )
	,"search_period"=>array("JP"=>"0","CN"=>"", "KR"=>"기간 검색", "EN" => "" )
	,"db_name"=>array("JP"=>"0","CN"=>"", "KR"=>"DB 이름", "EN" => "DB Name" )
	,"model_user"=>array("JP"=>"0","CN"=>"", "KR"=>"모델 유저", "EN" => "Model user" )
	,"search_option"=>array("JP"=>"0","CN"=>"", "KR"=>"검색 옵션", "EN" => "Model user" )
	,"count_text"=>array("JP"=>"0","CN"=>"", "KR"=>"숫자로", "EN" => "Model user" )
	,"by_id_text"=>array("JP"=>"0","CN"=>"", "KR"=>"아이디로", "EN" => "Model user" )
	,"manager_dept"=>array("JP"=>"0","CN"=>"", "KR"=>"담당자부서", "EN" => "Manager department" )
	,"query_title"=>array("JP"=>"0","CN"=>"", "KR"=>"쿼리명", "EN" => "Query title" )
	,"query_content"=>array("JP"=>"0","CN"=>"", "KR"=>"쿼리내용", "EN" => "query content" )
	,"query_content_ask_text"=>array("JP"=>"0","CN"=>"", "KR"=>"쿼리명를 입력하세요", "EN" => "Enter the query title" )
	,"saved_queries"=>array("JP"=>"0","CN"=>"", "KR"=>"저장된 쿼리", "EN" => "Saved queries" )
	,"query_search_result"=>array("JP"=>"0","CN"=>"", "KR"=>"쿼리 검색 결과", "EN" => "query search result" )
	,"information_consent_manag"=>array("JP"=>"0","CN"=>"", "KR"=>"안내 및 동의서 관리", "EN" => "" )
	,"bring_assets"=>array("JP"=>"0","CN"=>"", "KR"=>"자산반입", "EN" => "Bring Assets" )
	,"executives"=>array("JP"=>"0","CN"=>"", "KR"=>"임직원", "EN" => "Executives" )
	,"executivesinfo"=>array("JP"=>"0","CN"=>"", "KR"=>"임직원정보", "EN" => "임직원정보" )
	,"executives_en"=>array("JP"=>"0","CN"=>"", "KR"=>"임직원 영문명", "EN" => "Executives english name" )
	,"employee_affiliation"=>array("JP"=>"0","CN"=>"", "KR"=>"임직원 소속", "EN" => "Employee affiliation" )
	,"and_text"=>array("JP"=>"","CN"=>"", "KR"=>"외", "EN" => "and" )
	,"others"=>array("JP"=>"","CN"=>"", "KR"=>"인", "EN" => "others" )
	,"one"=>array("JP"=>"","CN"=>"", "KR"=>"외 1인", "EN" => "and_others_1" )
	,"two"=>array("JP"=>"","CN"=>"", "KR"=>"외 2인", "EN" => "and_others_2" )
	,"three"=>array("JP"=>"","CN"=>"", "KR"=>"외 3인", "EN" => "and_others_3" )
	,"four"=>array("JP"=>"","CN"=>"", "KR"=>"외 4인", "EN" => "and_others_4" )
	,"five"=>array("JP"=>"","CN"=>"", "KR"=>"외 5인", "EN" => "and_others_5" )
	,"kakao_employees"=>array("JP"=>"","CN"=>"", "KR"=>"카카오뱅크 임직원", "EN" => "Kakao Bank employee" )
	,"external_staff"=>array("JP"=>"","CN"=>"", "KR"=>"외부직원", "EN" => "External staff" )
	,"selectRequestTime"=>array("JP"=>"","CN"=>"", "KR"=>"요청시간 선텍", "EN" => "Select request time" )
	,"outsourcing_maganager"=>array("JP"=>"","CN"=>"", "KR"=>"외주관리 책임자", "EN" => "Outsourcing Management Manager" )
	,"on_site_agent"=>array("JP"=>"","CN"=>"", "KR"=>"현장대리인", "EN" => "On-site agent" )
	,"execute"=>array("JP"=>"","CN"=>"", "KR"=>"실행", "EN" => "execute" )
	,"query_execute"=>array("JP"=>"","CN"=>"", "KR"=>"쿼리 실행", "EN" => "Query execute" )
	,"search_part"=>array("JP"=>"","CN"=>"", "KR"=>"쿼리 부분", "EN" => "Search part" )
	,"item_management_number"=>array("JP"=>"","CN"=>"", "KR"=>"물품관리번호", "EN" => "Item management number" )
	,"expected_takeout_date"=>array("JP"=>"","CN"=>"", "KR"=>"반출예정일", "EN" => "Expected take-out date" )
	,"take_out"=>array("JP"=>"","CN"=>"", "KR"=>"반출", "EN" => "Take out" )
	,"model_name"=>array("JP"=>"","CN"=>"", "KR"=>"모델명", "EN" => "Model name" )
	,"date_out"=>array("JP"=>"","CN"=>"", "KR"=>"반출일자", "EN" => "Date out" )
	,"outer_name"=>array("JP"=>"","CN"=>"", "KR"=>"반출 처리자", "EN" => "반출 처리자" )
	,"downloading_text"=>array("JP"=>"","CN"=>"", "KR"=>"다운로드중", "EN" => "Downloading" )
	,"scantime_log"=>array("JP"=>"","CN"=>"", "KR"=>"검사 로그", "EN" => "Scan time log" )
	,"start_time"=>array("JP"=>"","CN"=>"", "KR"=>"시작 시간", "EN" => "Start time" )
	,"end_time"=>array("JP"=>"","CN"=>"", "KR"=>"종료 시간", "EN" => "End time" )
	,"complete_time"=>array("JP"=>"","CN"=>"", "KR"=>"소요 시간", "EN" => "Completion time" )
	,"count_enter_exit"=>array("JP"=>"","CN"=>"", "KR"=>"출입건수", "EN" => "Enter exit number" )
	,"sum_text"=>array("JP"=>"","CN"=>"", "KR"=>"합계", "EN" => "Sum" )
	,"day_text"=>array("JP"=>"","CN"=>"", "KR"=>"일별", "EN" => "Dayly" )
	,"month_text"=>array("JP"=>"","CN"=>"", "KR"=>"월별", "EN" => "Monthly" )
	,"rental_info_change_history"=>array("JP"=>"","CN"=>"", "KR"=>"물품대여정보변경내역", "EN" => "Rental information change history" )
	,"process_type_text"=>array("JP"=>"","CN"=>"", "KR"=>"처리구분", "EN" => "Processing type" )
	,"file_in_apply_list"=>array("JP"=>"","CN"=>"", "KR"=>"파일 반입 예외 신청내역", "EN" => "File In Apply List" )
	,"application_period"=>array("JP"=>"","CN"=>"", "KR"=>"적용기간", "EN" => "Application Period" )
	,"english_name"=>array("JP"=>"0","CN"=>"", "KR"=>"영문명", "EN" => "english name" )
	,"integrated_dashboard"=>array("JP"=>"","CN"=>"", "KR"=>"통합 대시보드", "EN" => "Integrated Dashboard" )
	,"gangnam_office"=>array("JP"=>"","CN"=>"", "KR"=>"강남 오피스", "EN" => "Gangnam Office" )
	,"pangyo_office"=>array("JP"=>"","CN"=>"", "KR"=>"판교 오피스", "EN" => "Pangyo Office" )
	,"gangbuk_office"=>array("JP"=>"","CN"=>"", "KR"=>"강북  오피스", "EN" => "Gangbuk Office" )
	,"IDC_center"=>array("JP"=>"","CN"=>"", "KR"=>"IDC 센터", "EN" => "IDC Center" )
	,"key_statistics"=>array("JP"=>"","CN"=>"", "KR"=>"주요 통계 ", "EN" => "key statistics" )
	,"visitor_visit"=>array("JP"=>"","CN"=>"", "KR"=>"방문자 출입", "EN" => "Visitor visit" )
	,"bring_out_good"=>array("JP"=>"","CN"=>"", "KR"=>"외부 자산 반입", "EN" => "Bring External Goods" )
	,"bring_goods"=>array("JP"=>"","CN"=>"", "KR"=>" 자산 반입", "EN" => "Bring External Goods" )
	,"tempoprary_pass_issue"=>array("JP"=>"","CN"=>"", "KR"=>"임시 출입증 발급", "EN" => "Issuance of a temporary pass" )
	,"tempoprary_pass"=>array("JP"=>"","CN"=>"", "KR"=>"출입증 발급", "EN" => "Temporary pass" )
	,"today_statistics"=>array("JP"=>"","CN"=>"", "KR"=>"오늘 통계", "EN" => "Today's statistics" )
	,"none_recovery_text"=>array("JP"=>"","CN"=>"", "KR"=>"미회수/ 미반출 현황", "EN" => "status of non-recovery/non-release" )
	,"mal_code"=>array("JP"=>"","CN"=>"", "KR"=>"악성코드 현황", "EN" => "Malicious code status" )
	,"vaccine_update_status"=>array("JP"=>"","CN"=>"", "KR"=>"백신 업데이트 현황", "EN" => "Vaccine update status" )
	,"file_exception_import"=>array("JP"=>"","CN"=>"", "KR"=>"파일 예외반입 신청현황", "EN" => "File exception import application status" )
	,"server_status"=>array("JP"=>"","CN"=>"", "KR"=>"서버현황", "EN" => "Server status" )
	,"work_log"=>array("JP"=>"","CN"=>"", "KR"=>"관리자작업내역", "EN" => "Administrator work history" )
	,"work_period"=>array("JP"=>"","CN"=>"", "KR"=>"작업기간", "EN" => "Work period" )
	,"work_detail"=>array("JP"=>"","CN"=>"", "KR"=>"작업내용", "EN" => "Work detail" )
	,"work_date"=>array("JP"=>"","CN"=>"", "KR"=>"작업일자", "EN" => "Work date" )
	,"workinfotext"=>array("JP"=>"","CN"=>"", "KR"=>"작업정보", "EN" => "Work info" )
	,"workertext"=>array("JP"=>"","CN"=>"", "KR"=>"작업자", "EN" => "worker" )
	,"workcallpagetext"=>array("JP"=>"","CN"=>"", "KR"=>"작업 호출 페이지", "EN" => "Action call page" )
	,"work_type"=>array("JP"=>"","CN"=>"", "KR"=>"작업유형", "EN" => "Work type" )
	,"idruletext"=>	array("JP"=>"ID must be entered with uppercase and lowercase letters and 5 to 12 numbers.", "CN"=>"ID 必须输入大小写字母和 5 到 12 位数字.", "KR"=>"아이디는 영문 대문자,소문자,숫자를 사용해 5~12자리로 입력해야합니다.", "EN" => "ID must be entered with uppercase and lowercase letters and 5 to 12 numbers." )
	,"passwordrules"=>		array("JP"=>"Enter a password within 8 to 16 characters, including three types of uppercase letters, lowercase letters, numbers, and special characters.", "CN"=>"输入 8 到 16 个字符的密码，包括大写字母、小写字母、数字和 3 个特殊字符.", "KR"=>"비밀번호는 영문대문자,영문소문자, 숫자, 특수문자 중 세가지를 포함해 8~16자 이내로 입력하세요.", "EN" => "Enter a password within 8 to 16 characters, including three types of uppercase letters, lowercase letters, numbers, and special characters." )
 	,"notvalidphonetext"=>	array("JP"=>"It is not a valid Phone Number format.", "CN"=>"这不是有效的电话号码格式", "KR"=>"올바른 전화번호 형식이 아닙니다.", "EN" => "It is not a valid Phone Number format." )
	,"notvalidemailtext"=>	array("JP"=>"It is not a valid Email address format.", "CN"=>"这不是有效的电子邮件地址格式.", "KR"=>"올바른 Email 주소 형식이 아닙니다.", "EN" => "It is not a valid Email address format." )
	,"app_update_log_text"=>array("JP"=>"", "CN"=>"", "KR"=>"App업데이트내역", "EN" => "App Update Log" )
	,"update_date"=>array("JP"=>"", "CN"=>"", "KR"=>"업데이트일자", "EN" => "Update Date" )
	,"update_target"=>array("JP"=>"", "CN"=>"", "KR"=>"업데이트 대상", "EN" => "Update Target" )
	,"work_classification"=>array("JP"=>"", "CN"=>"", "KR"=>"작업구분", "EN" => "work classification" )
	,"work_log_text"=>array("JP"=>"", "CN"=>"", "KR"=>"작업내역", "EN" => "" )
	,"usb_count"=>array("JP"=>"", "CN"=>"", "KR"=>"보안 USB", "EN" => "" )
	,"pass_count"=>array("JP"=>"", "CN"=>"", "KR"=>"임시 출입증", "EN" => "" )
	,"rent_count"=>array("JP"=>"", "CN"=>"", "KR"=>"물품 미회수", "EN" => "" )
	,"goods_count"=>array("JP"=>"", "CN"=>"", "KR"=>"자산 미반출", "EN" => "" )
	,"exp_file_in_count_text"=>array("JP"=>"", "CN"=>"", "KR"=>"예외 반입 파일", "EN" => "" )
	,"update_date_text"=>array("JP"=>"", "CN"=>"", "KR"=>"업데이트 일시", "EN" => "" )
	,"disk_free_text"=>array("JP"=>"", "CN"=>"", "KR"=>"Disk Free", "EN" => "Disk Free" )
	,"total_text"=>array("JP"=>"", "CN"=>"", "KR"=>"Total", "EN" => "Total" )
	,"free_text"=>array("JP"=>"", "CN"=>"", "KR"=>"Free", "EN" => "Free" )
	,"web_connection_text"=>array("JP"=>"", "CN"=>"", "KR"=>"Web Connection", "EN" => "Web Connection" )
	,"db_connection_text"=>array("JP"=>"", "CN"=>"", "KR"=>"DB Connection", "EN" => "DB Connection" )
	,"submit_text"=>array("JP"=>"", "CN"=>"", "KR"=>"제출", "EN" => "Submit" )
	,"unsubmit_text"=>array("JP"=>"", "CN"=>"", "KR"=>"제출안함", "EN" => "Un Submit" )
	,"center_location"=>array("JP"=>"", "CN"=>"", "KR"=>"센터위치", "EN" => "Center Location" )
	,"write_pledge_text"=>array("JP"=>"", "CN"=>"", "KR"=>"서약서 작성여부", "EN" => "write pledge" )
	,"pledge_contract_name_text"=>array("JP"=>"", "CN"=>"", "KR"=>"서약서 계약명", "EN" => "pledge contract name" )
	,"pledge_contract_company_text"=>array("JP"=>"", "CN"=>"", "KR"=>"서약서 회사명", "EN" => "pledge contract company" )
	,"pledge_author_text"=>array("JP"=>"", "CN"=>"", "KR"=>"서약서 이름", "EN" => "pledge author" )
	,"pledge_date_text"=>array("JP"=>"", "CN"=>"", "KR"=>"서약서 작성일", "EN" => "pledge date" )
	,"personel_info_consent_text"=>array("JP"=>"", "CN"=>"", "KR"=>"개인정보 동의서 작성여부", "EN" => "Personel Information consent" )
	,"personel_info_date_text"=>array("JP"=>"", "CN"=>"", "KR"=>"개인정보 동의서 작성일자", "EN" => "Personel Information Date" )
	,"info_protec_pledge_text"=>array("JP"=>"", "CN"=>"", "KR"=>"정보보호서약서 작성여부", "EN" => "Information Protection Pledge" )
	,"info_protec_pledge_date_text"=>array("JP"=>"", "CN"=>"", "KR"=>"정보보호서약서 작성일자", "EN" => "Information Protection Pledge Date" )
	,"agree_text"=>array("JP"=>"", "CN"=>"", "KR"=>"동의", "EN" => "Agree" )
	,"dis_agree_text"=>array("JP"=>"", "CN"=>"", "KR"=>"미동의", "EN" => "Disagree" )
	,"process_time"=>array("JP"=>"", "CN"=>"", "KR"=>"처리 시간", "EN" => "processing time" )
	,"verifier_name"=>array("JP"=>"", "CN"=>"", "KR"=>"확인자 이름", "EN" => "Verifier name" )
	,"verifier_id"=>array("JP"=>"", "CN"=>"", "KR"=>"확인자 아이디", "EN" => "Verifier ID" )
	,"end_date_text"=>array("JP"=>"", "CN"=>"", "KR"=>"완료시간", "EN" => "End Date" )
	,"result_text"=>array("JP"=>"", "CN"=>"", "KR"=>"결과", "EN" => "Result" )
	,"madeby_pe"=>array("JP"=>"", "CN"=>"", "KR"=>"PE 제작", "EN" => "Made by PE" )
	,"produce_text"=>array("JP"=>"", "CN"=>"", "KR"=>"제작", "EN" => "Produce" )
	,"certify_text"=>array("JP"=>"", "CN"=>"", "KR"=>"인증", "EN" => "Produce" )
	,"user_id_key_text"=>array("JP"=>"", "CN"=>"", "KR"=>"User ID", "EN" => "User ID" )
	,"usb_id_text"=>array("JP"=>"", "CN"=>"", "KR"=>"USB ID", "EN" => "USB ID" )
	,"key_text"=>array("JP"=>"", "CN"=>"", "KR"=>"KEY", "EN" => "KEY" )
	,"manager_text"=>array("JP"=>"", "CN"=>"", "KR"=>"처리자", "EN" => "" )
	,"user_id_validate"=>array("JP"=>"", "CN"=>"", "KR"=>" User ID(KEY)를 입력하세요.", "EN" => "" )
	,"usb_id_validate"=>array("JP"=>"", "CN"=>"", "KR"=>" USB ID를 입력하세요.", "EN" => "" )
	,"scancenterdiv"=>array("JP"=>"","CN"=>"", "KR"=>"검사장구분", "EN" => "" )
	,"scan_import_fail"=>array("JP"=>"","CN"=>"", "KR"=>"반입실패", "EN" => "" )
); 

?>
